"use client";
import Link from "next/link";
import {useEffect,useState,type FormEvent} from "react";
import {useDeFi} from "./DeFiContext";
import {PublicNav} from "./PublicNav";
import {FrontierChart} from "./FrontierChart";
import {BoundedMonitor} from "./BoundedMonitor";
import {api,ApiError} from "@/lib/api";
import {scenario,frontier,format,metrics,type Snapshot,type Metrics} from "../../../supabase/functions/rivexis-api/defi-model.mjs";
import {sampleSnapshot} from "../../../supabase/functions/rivexis-api/defi-sample.mjs";

type View="portfolio"|"scenarios"|"frontier"|"transactions"|"reports";
const tabs:[View,string,string][]=[["portfolio","Portfolio Intelligence","01"],["scenarios","Risk Scenario Lab","02"],["frontier","Defense Frontier","03"],["transactions","Transaction Intelligence","04"],["reports","Monitoring & Reports","05"]];
const money=(v:unknown)=>typeof v==="string"?`$${Number(format(v)).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`:"—";
const hf=(v:unknown)=>typeof v==="string"?format(v,18,3):"No debt";
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function publicRequest<T>(path:string,input:unknown):Promise<T>{const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input),signal:AbortSignal.timeout(35000)});const body=await r.json();if(!r.ok)throw new Error(body.detail||"Evidence unavailable");return body as T}
export function DeFiWorkspace({initialView="portfolio",authenticated=false}:{initialView?:View;authenticated?:boolean}){
  const c=useDeFi(),s=c.snapshot;
  const [view,setView]=useState<View>(initialView),[address,setAddress]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[clock,setClock]=useState(Date.now());
  const [asset,setAsset]=useState(""),[kind,setKind]=useState("repay"),[amount,setAmount]=useState(""),[preview,setPreview]=useState<Record<string,unknown>|null>(null),[reports,setReports]=useState<{id:string;created_at:string;receipt:unknown}[]>([]);
  useEffect(()=>{setView(initialView)},[initialView]);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),10000);return()=>clearInterval(timer)},[]);
  const stale=!!s&&!s.sample&&(clock/1000-s.blockTimestamp>180),ready=!!s&&s.status==="READY"&&!stale;
  const reserves=s?.positions.flatMap(p=>p.reserves)??[];
  let outcomes:Metrics[]=[];try{if(ready)outcomes=scenario(s!,c.shocks,[],s?.sample?s.blockTimestamp*1000:clock)}catch{}
  const selectedAsset=asset||reserves.find(r=>BigInt(r.debtRaw)>0n)?.asset||reserves[0]?.asset||"";
  function reset(){c.setShocks({});c.setResult(null);setPreview(null);setError("");setNotice("");setAsset("")}
  function sample(){reset();c.setSnapshot(sampleSnapshot());setView("portfolio")}
  async function inspect(e?:FormEvent){e?.preventDefault();if(!/^0x[\da-fA-F]{40}$/.test(address)){setError("Enter a complete Ethereum wallet address.");return}setLoading(true);reset();c.setSnapshot(null);try{c.setSnapshot(await publicRequest<Snapshot>("/api/v1/defi/snapshot",{wallet:address}))}catch(e){setError(e instanceof Error?e.message:"Unable to read protocol evidence")}finally{setLoading(false)}}
  async function connect(){try{const ethereum=(window as Window&{ethereum?:{request:(v:{method:string})=>Promise<string[]>}}).ethereum;if(!ethereum){setError("No browser wallet found. Paste a public address to continue.");return}const accounts=await ethereum.request({method:"eth_requestAccounts"});setAddress(accounts[0]||"");setNotice("Address selected. Inspect it when ready. No signature was requested.")}catch{setError("Wallet access was declined or unavailable")}}
  function compare(){setError("");try{if(!ready)throw new Error("Refresh supported evidence before comparing alternatives");c.setResult(frontier(s!,{budget:c.budget,target:c.target,gasReserve:c.fee,shocks:c.shocks,objective:c.objective},s?.sample?s.blockTimestamp*1000:clock))}catch(e){setError(e instanceof Error?e.message:"Constraints could not be evaluated")}}
  async function transaction(){setError("");setPreview(null);if(!ready||s?.sample){setError("GasGuard requires a fresh live supported wallet snapshot. Educational samples cannot be simulated.");return}setLoading(true);try{setPreview(await publicRequest("/api/v1/defi/transaction",{wallet:s.wallet,asset:selectedAsset,kind,amount}))}catch(e){setError(e instanceof Error?e.message:"Transaction preview unavailable")}finally{setLoading(false)}}
  async function loadReports(){setError("");setLoading(true);try{const r=await api<{items:typeof reports}>("/api/v1/defi-reports");setReports(r.items)}catch(e){setError(e instanceof ApiError&&e.status===401?"Log in to access your saved reports.":"Saved reports could not load.")}finally{setLoading(false)}}
  async function save(){setError("");setNotice("");if(!c.result||!ready){setError("Calculate a fresh Defense Frontier comparison first.");return}setLoading(true);try{const result=await api<{id:string}>("/api/v1/defi-reports",{method:"POST",body:JSON.stringify({wallet:s!.wallet,sample:s!.sample===true,budget:c.budget,target:c.target,gasReserve:c.fee,shocks:c.shocks,objective:c.objective})});setNotice(`Report saved: ${result.id}. Live reports are recomputed from fresh server evidence.`);await loadReports()}catch(e){setError(e instanceof ApiError&&e.status===401?"Log in to save reports. You can export a receipt without an account.":e instanceof Error?e.message:"Report could not be saved")}finally{setLoading(false)}}
  const receipt=()=>({brand:"RIVEXIS",classification:s?.sample?"HYPOTHETICAL_SAMPLE":"MODEL_COMPARISON_NOT_EXECUTION",snapshot:s,constraints:{budget:c.budget,target:c.target,gasReserve:c.fee,shocks:c.shocks,objective:c.objective},result:c.result,createdAt:new Date().toISOString()});
  return <>{!authenticated&&<PublicNav/>}<div className={authenticated?"defiWorkspace":"defiWorkspace anonymousWorkspace"}>
    <header className="instrumentHeader"><div><div className="eyebrow">RISK · VALUE · EXECUTION · ANALYSIS</div><h1>{tabs.find(t=>t[0]===view)?.[1]}</h1><p>Understand the risk. Explore the alternatives. Decide with evidence.</p></div><span className="modeLabel">Ethereum / Aave V3<span>Read-only · Free bounded beta</span></span></header>
    {!authenticated&&<nav className="instrumentTabs" aria-label="Risk workspace">{tabs.map(([key,label,n])=><button key={key} type="button" aria-current={view===key?"page":undefined} className={view===key?"selected":""} onClick={()=>{setView(key);setError("")}}><small>{n}</small>{label}</button>)}</nav>}
    <section className="lookupBar" aria-label="Wallet inspection"><form onSubmit={inspect}><label htmlFor="wallet-address">Public Ethereum address</label><div className="lookupControls"><input id="wallet-address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="0x…" autoComplete="off" spellCheck={false} maxLength={42}/><button className="button" disabled={loading} type="submit">{loading?"Reading evidence…":"Inspect wallet"}<span aria-hidden="true">↗</span></button></div></form><div className="lookupSecondary"><button className="textButton" type="button" onClick={sample}>Explore a hypothetical sample</button><button className="textButton" type="button" onClick={connect}>Connect read-only wallet</button></div></section>
    {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}
    {s&&<div className={`evidenceStrip ${s.sample?"sample":""}`}><strong>{s.sample?"HYPOTHETICAL SAMPLE · NOT LIVE":stale?"STALE SNAPSHOT":s.status==="READY"?"ON-CHAIN SNAPSHOT":"UNSUPPORTED MODEL"}</strong><span>{s.sample?"Invented educational inputs":`Block ${s.blockNumber} · ${new Date(s.blockTimestamp*1000).toLocaleTimeString()} · Ethereum`}</span>{!s.sample&&<button className="textButton" type="button" disabled={loading} onClick={()=>{void publicRequest<Snapshot>("/api/v1/defi/snapshot",{wallet:s.wallet}).then(next=>{c.setSnapshot(next);c.setResult(null);setPreview(null)}).catch(e=>setError(e.message))}}>Refresh evidence ↻</button>}</div>}
    {s?.warnings?.map((w,i)=><div className="warning" key={i}>{w}</div>)}{stale&&<div className="warning">This snapshot is older than three minutes. Scenario and action calculations are withheld until refreshed.</div>}
    {!s?<section className="emptyInstrument"><div className="largeIndex">{tabs.find(t=>t[0]===view)?.[2]}</div><div><div className="eyebrow">BEGIN WITH A POSITION</div><h2>Your exposure, in perspective.</h2><p>Inspect a public Ethereum address to discover Aave V3 lending exposure. Or learn the full scenario and Defense Frontier workflow with a clearly labeled hypothetical portfolio.</p><p className="muted">No custody. No signing. No fabricated live results.</p></div></section>:<>
      {view==="portfolio"&&<>
        <section className="metricRibbon" aria-label="Observed portfolio metrics"><div><span>Collateral value</span><strong>{money(s.observedCollateralRaw)}</strong><small>Aave oracle / USD</small></div><div><span>Borrowing exposure</span><strong>{money(s.observedDebtRaw)}</strong><small>Debt accrued at the block</small></div><div><span>Observed health factor</span><strong>{hf(s.observedHealthFactorRaw)}</strong><small>Liquidation eligibility below 1.000</small></div><div><span>Native gas balance</span><strong>{format(s.nativeBalanceRaw,18,4)} <em>ETH</em></strong><small>Public wallet balance</small></div></section>
        <section className="instrumentPanel"><div className="sectionHeading"><div><div className="eyebrow">LIQUIDATIONGUARD</div><h2>Lending exposure</h2></div><button className="textButton" type="button" onClick={()=>setView("scenarios")}>Stress-test this position →</button></div>{!reserves.length?<p>No open Aave V3 position was found at this block. This does not imply that the wallet has no exposure on other protocols or chains.</p>:<div className="tableScroll"><table><thead><tr><th>Asset</th><th>Supplied</th><th>Borrowed</th><th>Oracle price</th><th>Liquidation threshold</th><th>Evidence</th></tr></thead><tbody>{reserves.map(r=><tr key={r.asset}><td><b>{r.symbol}</b><small>{r.collateralEnabled?"Collateral enabled":"Not collateral"}</small></td><td>{format(r.collateralRaw,r.decimals,4)}</td><td>{format(r.debtRaw,r.decimals,4)}</td><td>{money(r.priceRaw)}</td><td>{(Number(r.ltBps)/100).toFixed(2)}%</td><td>{r.oracleState}</td></tr>)}</tbody></table></div>}</section>
        <div className="twoColumns"><section className="instrumentPanel"><div className="eyebrow">CAPITAL, WITH CONTEXT</div><h2>See what changes the outcome.</h2><p>Debt repayment and collateral supply have different effects on stressed health. Compare them against your own budget and target.</p><button className="button" type="button" onClick={()=>setView("frontier")}>Open Defense Frontier →</button></section><section className="instrumentPanel"><div className="eyebrow">COVERAGE BOUNDARY</div><h2>Know what is supported.</h2><p>Ethereum Aave V3 normal mode. eMode, isolation, Morpho, other chains and unvalidated oracle sources remain unsupported for modeling.</p><Link className="textButton" href="/methodology">Read the methodology ↗</Link></section></div>
      </>}
      {view==="scenarios"&&<>
        <section className="instrumentPanel"><div className="sectionHeading"><div><div className="eyebrow">DETERMINISTIC STRESS TEST</div><h2>Define the market you want to test.</h2></div><button className="textButton" onClick={()=>{c.setShocks({});c.setResult(null)}} type="button">Reset scenario</button></div><p>A shock affects every collateral and debt balance denominated in that token. These are user assumptions, not forecasts.</p><div className="scenarioGrid">{reserves.map(r=><label className="shockControl" key={r.asset}><span>{r.symbol} price shock <strong>{(c.shocks[r.asset.toLowerCase()]??0)/100}%</strong></span><input aria-label={`${r.symbol} price shock`} type="range" min="-9500" max="10000" step="100" value={c.shocks[r.asset.toLowerCase()]??0} disabled={!ready} onChange={e=>{c.setShocks({...c.shocks,[r.asset.toLowerCase()]:Number(e.target.value)});c.setResult(null)}}/><span className="rangeLabels"><small>−95%</small><small>Unchanged</small><small>+100%</small></span></label>)}</div></section>
        <section className="instrumentPanel"><div className="eyebrow">BEFORE / UNDER YOUR SCENARIO</div><h2>Position risk, without netting.</h2>{s.positions.map((p,i)=>{const base=metrics(p),o=outcomes[i];return <div className="scenarioResult" key={p.id}><div><span>Aave V3 / Ethereum</span><h3>Health factor</h3><strong>{hf(s.observedHealthFactorRaw)} <span aria-hidden="true">→</span> {o?hf(o.healthFactorRaw):"Withheld"}</strong></div><div><span>Stressed collateral</span><strong>{o?money(o.collateralRaw):"—"}</strong></div><div><span>Stressed debt</span><strong>{o?money(o.debtRaw):"—"}</strong></div><div className={o?.liquidatable?"dangerText":""}>{o?.liquidatable?"Below modeled liquidation threshold":o?"Liquidation threshold not crossed in this scenario":"Supported fresh evidence required"}</div></div>})}<button className="button" type="button" onClick={()=>setView("frontier")}>Compare defensive alternatives →</button></section>
      </>}
      {view==="frontier"&&<>
        <section className="frontierIntro"><div className="eyebrow">THE RIVEXIS DEFENSE FRONTIER</div><h2>What can your capital change?</h2><p>Compare balance-constrained repayment and collateral alternatives under your chosen scenario. Every result retains its costs, assumptions and remaining modeled risk.</p></section>
        <section className="instrumentPanel"><form className="constraintForm" onSubmit={e=>{e.preventDefault();compare()}}><label className="field">Capital budget / USD<input value={c.budget} onChange={e=>{c.setBudget(e.target.value);c.setResult(null)}} inputMode="decimal" required/></label><label className="field">Target health factor<input value={c.target} onChange={e=>{c.setTarget(e.target.value);c.setResult(null)}} inputMode="decimal" required/></label><label className="field">Assumed total fee reserve / USD<input value={c.fee} onChange={e=>{c.setFee(e.target.value);c.setResult(null)}} inputMode="decimal" required/></label><label className="field">Risk objective<select value={c.objective} onChange={e=>{c.setObjective(e.target.value);c.setResult(null)}}><option value="target">Least capital found to reach target</option><option value="max-min">Highest minimum health factor found</option></select></label><button className="button" disabled={!ready} type="submit">Calculate alternatives ↗</button></form><p className="muted">Current price shocks: {reserves.map(r=>`${r.symbol} ${(c.shocks[r.asset.toLowerCase()]??0)/100}%`).join(" · ")||"None"}. <button className="textButton" type="button" onClick={()=>setView("scenarios")}>Edit scenario</button></p><p className="muted">Only existing eligible wallet balances are allocated. No hypothetical purchases or swaps. The fee reserve is your assumption; execution requires GasGuard.</p></section>
        {c.result&&ready&&<><div className="sectionHeading"><div><div className="eyebrow">{c.result.examined} ALLOCATIONS EXAMINED</div><h2>{c.result.meetsTarget?"Target-reaching alternatives found.":"No alternative found that reaches your target."}</h2></div><button className="ghost" type="button" onClick={()=>download(receipt(),"rivexis-risk-receipt.json")}>Export evidence</button></div><FrontierChart result={c.result}/><div className="frontierResults">{c.result.alternatives.map((a,i)=><article className="alternative" key={i}><div className="alternativeRank">{String(i+1).padStart(2,"0")}<span>MODELED ONLY</span></div><div className="alternativeBody"><h3>{a.actions.map(x=>`${x.kind==="repay"?"Repay":"Supply"} ${format(x.amountRaw,x.decimals,4)} ${x.symbol}`).join(" + ")}</h3><p>{a.meetsTarget?"Meets the selected modeled target":"Target remains unmet"} · {a.uncovered} positions below target</p><div className="alternativeMetrics"><div><span>Capital + assumed fees</span><b>{money(a.totalBudgetRaw)}</b></div><div><span>Minimum stressed health</span><b>{hf(a.minHealthFactorRaw)}</b></div><div><span>Execution</span><b>Not simulated</b></div></div>{a.actions.some(x=>x.approvalRequired)&&<small className="warningText">Separate token approval required; fees may exceed your assumed reserve.</small>}</div><button className="textButton" type="button" disabled={!!s.sample||a.actions.length!==1} onClick={()=>{const x=a.actions[0];setKind(x.kind);setAsset(x.asset);setAmount(format(x.amountRaw,x.decimals,x.decimals));setView("transactions");setPreview(null)}}>{s.sample?"Sample only":a.actions.length>1?"Preview each action separately":"Preview action →"}</button></article>)}</div>{!c.result.alternatives.length&&<div className="warning">No eligible balance-constrained action was found. Wallet balances, collateral eligibility or the available budget prevent a supported alternative.</div>}<p className="muted">{c.result.method}</p>{c.result.warnings.map(w=><p className="muted" key={w}>{w}</p>)}</>}
      </>}
      {view==="transactions"&&<>
        <section className="instrumentPanel"><div className="eyebrow">GASGUARD / PRE-EXECUTION INTELLIGENCE</div><h2>Preview the action. Keep the decision.</h2><p>Read-only RPC calls and gas estimates for supported Aave actions. Rivexis never signs or submits the transaction.</p><form className="constraintForm" onSubmit={e=>{e.preventDefault();void transaction()}}><label className="field">Action<select value={kind} onChange={e=>{setKind(e.target.value);setPreview(null)}}><option value="repay">Repay variable debt</option><option value="supply">Supply existing collateral</option><option value="withdraw">Withdraw collateral</option><option value="borrow">Borrow variable debt</option></select></label><label className="field">Asset<select value={selectedAsset} onChange={e=>{setAsset(e.target.value);setPreview(null)}}>{reserves.map(r=><option key={r.asset} value={r.asset}>{r.symbol}</option>)}</select></label><label className="field">Token amount<input value={amount} onChange={e=>{setAmount(e.target.value);setPreview(null)}} required inputMode="decimal" placeholder="0.00"/></label><button className="button" disabled={loading||!ready||!!s.sample} type="submit">{loading?"Simulating…":"Preview transaction ↗"}</button></form>{!!s.sample&&<p className="warning">Live RPC simulations are unavailable for hypothetical samples. Inspect a real supported wallet.</p>}</section>
        {preview&&<section className="instrumentPanel" aria-live="polite"><div className="eyebrow">{String(preview.status)}</div><h2>{String(preview.simulation).replaceAll("_"," ")}</h2><div className="metricRibbon"><div><span>Health before</span><strong>{hf((preview.before as Metrics)?.healthFactorRaw)}</strong></div><div><span>Modeled health after</span><strong>{hf((preview.after as Metrics)?.healthFactorRaw)}</strong></div><div><span>Gas units</span><strong>{String(preview.gasRaw??"Unknown")}</strong></div><div><span>Gas fee reserve</span><strong>{typeof preview.feeReserveWei==="string"?`${format(preview.feeReserveWei,18,6)} ETH`:"Unknown"}</strong></div></div>{(preview.blockers as string[]).map(b=><div key={b} className="warning">{b}</div>)}{(preview.warnings as string[]).map(w=><p className="muted" key={w}>{w}</p>)}<button className="ghost" type="button" onClick={()=>download(preview,"rivexis-transaction-preview.json")}>Export transaction evidence</button></section>}
      </>}
      {view==="reports"&&<>
        <section className="instrumentPanel"><div className="eyebrow">MONITORING / HISTORY / REPORTS</div><h2>A decision deserves a record.</h2><p>Export a reproducible risk receipt with raw snapshot inputs, scenario assumptions, alternatives and model identity. Account reports are private to their owner, with a 20-report limit.</p><div className="inlineActions"><button className="button" type="button" disabled={!c.result||!ready||loading} onClick={save}>{loading?"Saving…":"Save comparison to account"}</button><button className="ghost" type="button" disabled={!c.result} onClick={()=>download(receipt(),"rivexis-risk-receipt.json")}>Export JSON receipt</button><button className="textButton" type="button" disabled={loading} onClick={loadReports}>Load saved reports</button></div><p className="muted">Live saved reports are recalculated on the server from fresh chain evidence. Educational receipts are labeled hypothetical. No financial state is automatically persisted in your browser.</p></section>
        <section className="instrumentPanel"><h2>Historical evidence & notifications</h2><p>Existing account notifications and historical records are retained. Automated DeFi risk emails and server-side continuous monitoring remain disabled.</p>{authenticated?<Link className="textButton" href="/workspace/history">Review retained historical analyses →</Link>:<Link className="textButton" href="/login">Log in for account history →</Link>}</section>
        <BoundedMonitor/>{reports.length>0&&<section className="instrumentPanel"><h2>Saved comparisons</h2>{reports.map(r=><div className="savedReport" key={r.id}><div><b>{r.id}</b><small>{new Date(r.created_at).toLocaleString()}</small></div><button className="ghost" onClick={()=>download(r.receipt,`rivexis-${r.id}.json`)} type="button">Export</button></div>)}</section>}
      </>}
      <details className="evidenceDetails"><summary>Evidence, model assumptions & coverage</summary><dl><dt>Model</dt><dd>{s.model}</dd><dt>Snapshot identity</dt><dd>{s.blockHash}</dd><dt>Wallet</dt><dd>{s.wallet}</dd><dt>Provider</dt><dd>{String(s.rpcHost??"Educational fixture")}</dd><dt>Oracle unit</dt><dd>USD / 10⁸; token amounts retained in native decimals</dd></dl><p>Aave health factor = collateral × weighted liquidation threshold ÷ debt, with Aave integer rounding. Separate positions are never netted. Interest is accrued at the snapshot block; future interest, parameter changes and unknown oracle behavior remain outside the model.</p><button className="textButton" type="button" onClick={()=>download(s,"rivexis-snapshot.json")}>Export raw snapshot →</button></details>
    </>}
    <footer className="instrumentFooter"><span>RIVEXIS · Free access, bounded usage.</span><span>Financial modeling only. No guarantee of safety or execution.</span></footer>
  </div></>;
}
