"use client";
import Link from "next/link";
import {useEffect,useState,useRef,type FormEvent} from "react";
import {useDeFi} from "./DeFiContext";
import {PublicNav} from "./PublicNav";
import {FrontierChart} from "./FrontierChart";
import {BoundedMonitor} from "./BoundedMonitor";
import {api,ApiError} from "@/lib/api";
import {scenario,frontier,format,metrics,type Snapshot,type Metrics} from "../../../supabase/functions/rivexis-api/defi-unified-model.mjs";
import {sampleSnapshot} from "../../../supabase/functions/rivexis-api/defi-sample.mjs";

type View="portfolio"|"scenarios"|"frontier"|"transactions"|"reports";
const tabs:[View,string,string][]=[["portfolio","Portfolio Intelligence","01"],["scenarios","Risk Scenario Lab","02"],["frontier","Defense Frontier","03"],["transactions","Transaction Intelligence","04"],["reports","Monitoring & Reports","05"]];
const money=(v:unknown)=>{if(typeof v!=="string")return "—";const [whole,fraction]=format(v,8,2).split('.');return `$${whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')}.${fraction}`};
const oraclePrice=(v:string)=>{const [whole,fraction]=format(v,8,8).split('.');return `$${whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')}.${fraction}`};
const tokenAmount=(v:string,decimals:number,maxPlaces=8)=>{const places=Math.min(decimals,maxPlaces),unit=10n**BigInt(decimals-places);return BigInt(v)>0n&&BigInt(v)<unit?`<${format(unit,decimals,places)}`:format(v,decimals,places)};
const hf=(v:unknown)=>typeof v==="string"?format(v,18,3):"No debt";
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function liveRequest<T>(path:string,input:unknown):Promise<T>{return api<T>(path,{method:"POST",body:JSON.stringify(input),signal:AbortSignal.timeout(35000)})}
export function DeFiWorkspace({initialView="portfolio",authenticated=false,demoOnly=false}:{initialView?:View;authenticated?:boolean;demoOnly?:boolean}){
  const c=useDeFi(),s=c.snapshot;
  const alive=useRef(true);useEffect(()=>{alive.current=true;return ()=>{alive.current=false}},[]);
  const [view,setView]=useState<View>(initialView),[address,setAddress]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[clock,setClock]=useState(Date.now());
  const [coverage,setCoverage]=useState("aave"),[positionId,setPositionId]=useState(""),[shares,setShares]=useState<string|undefined>(),[asset,setAsset]=useState(""),[kind,setKind]=useState("repay"),[amount,setAmount]=useState(""),[preview,setPreview]=useState<Record<string,unknown>|null>(null),[reports,setReports]=useState<{id:string;created_at:string;receipt:unknown}[]>([]);
  useEffect(()=>{setView(initialView)},[initialView]);
  useEffect(()=>{if(typeof s?.coverage==='string')setCoverage(s.coverage)},[s?.coverage]);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),10000);return()=>clearInterval(timer)},[]);
  const stale=!!s&&!s.sample&&(clock/1000-s.blockTimestamp>180),ready=!!s&&s.status==="READY"&&!stale;
  const reserves=s?.positions.flatMap(p=>p.reserves)??[];
  const uniqueReserves=[...new Map(reserves.map(r=>[r.asset.toLowerCase(),r])).values()];
  const selectedPosition=s?.positions.find(p=>p.id===positionId)??s?.positions[0];
  const transactionReserves=selectedPosition?.reserves??[];
  let outcomes:Metrics[]=[];try{if(ready)outcomes=scenario(s!,c.shocks,[],s?.sample?s.blockTimestamp*1000:clock)}catch{}
  const selectedAsset=transactionReserves.find(r=>r.asset===asset)?.asset||transactionReserves.find(r=>BigInt(r.debtRaw)>0n)?.asset||transactionReserves[0]?.asset||"";
  function reset(){c.setShocks({});c.setResult(null);setPreview(null);setError("");setNotice("");setAsset("");setPositionId("");setShares(undefined)}
  function sample(){reset();c.setSnapshot(sampleSnapshot());setView("portfolio")}
  async function inspect(e?:FormEvent){e?.preventDefault();if(!/^0x[\da-fA-F]{40}$/.test(address)){setError("Enter a complete Ethereum wallet address.");return}setLoading(true);reset();c.setSnapshot(null);try{const next=await liveRequest<Snapshot>("/api/v1/defi/snapshot",{wallet:address,coverage});if(alive.current)c.setSnapshot(next)}catch(e){setError(e instanceof Error?e.message:"Unable to read protocol evidence")}finally{setLoading(false)}}
  async function refresh(){if(!s||loading)return;setLoading(true);setError("");try{const next=await liveRequest<Snapshot>("/api/v1/defi/snapshot",{wallet:s.wallet,coverage:s.coverage??'aave'});if(alive.current){c.setSnapshot(next);c.setResult(null);setPreview(null)}}catch(e){setError(e instanceof Error?e.message:"Evidence unavailable")}finally{setLoading(false)}}
  async function connect(){try{const ethereum=(window as Window&{ethereum?:{request:(v:{method:string})=>Promise<string[]>}}).ethereum;if(!ethereum){setError("No browser wallet found. Paste a public address to continue.");return}const accounts=await ethereum.request({method:"eth_requestAccounts"});setAddress(accounts[0]||"");setNotice("Address selected. Inspect it when ready. No signature was requested.")}catch{setError("Wallet access was declined or unavailable")}}
  function compare(){setError("");try{if(!ready)throw new Error("Refresh supported evidence before comparing alternatives");c.setResult(frontier(s!,{budget:c.budget,target:c.target,gasReserve:c.fee,shocks:c.shocks,objective:c.objective},s?.sample?s.blockTimestamp*1000:clock))}catch(e){setError(e instanceof Error?e.message:"Constraints could not be evaluated")}}
  async function transaction(){setError("");setPreview(null);if(!ready||s?.sample){setError("GasGuard requires a fresh live supported wallet snapshot. Educational samples cannot be simulated.");return}setLoading(true);try{setPreview(await liveRequest("/api/v1/defi/transaction",{wallet:s.wallet,coverage:s.coverage??'aave',positionId:selectedPosition?.id,asset:selectedAsset,kind,amount,...(shares?{sharesRaw:shares}:{})}))}catch(e){setError(e instanceof Error?e.message:"Transaction preview unavailable")}finally{setLoading(false)}}
  async function loadReports(){setError("");setLoading(true);try{const r=await api<{items:typeof reports}>("/api/v1/defi-reports");setReports(r.items)}catch(e){setError(e instanceof ApiError&&e.status===401?"Log in to access your saved reports.":"Saved reports could not load.")}finally{setLoading(false)}}
  async function save(){setError("");setNotice("");if(!c.result||!ready){setError("Calculate a fresh Defense Frontier comparison first.");return}setLoading(true);try{const result=await api<{id:string}>("/api/v1/defi-reports",{method:"POST",body:JSON.stringify({wallet:s!.wallet,coverage:s!.coverage??"aave",sample:s!.sample===true,budget:c.budget,target:c.target,gasReserve:c.fee,shocks:c.shocks,objective:c.objective})});setNotice(`Report saved: ${result.id}. Live reports are recomputed from fresh server evidence.`);await loadReports()}catch(e){setError(e instanceof ApiError&&e.status===401?"Log in to save reports. You can export a receipt without an account.":e instanceof Error?e.message:"Report could not be saved")}finally{setLoading(false)}}
  const receipt=()=>({brand:"RIVEXIS",classification:s?.sample?"HYPOTHETICAL_SAMPLE":"MODEL_COMPARISON_NOT_EXECUTION",snapshot:s,constraints:{budget:c.budget,target:c.target,gasReserve:c.fee,shocks:c.shocks,objective:c.objective},result:c.result,createdAt:new Date().toISOString()});
  return <>{!authenticated&&<PublicNav/>}<div className={authenticated?"defiWorkspace":"defiWorkspace anonymousWorkspace"}>
    <header className="instrumentHeader"><div><div className="eyebrow">RISK · VALUE · EXECUTION · ANALYSIS</div><h1>{tabs.find(t=>t[0]===view)?.[1]}</h1><p>Understand the risk. Explore the alternatives. Decide with evidence.</p></div><span className="modeLabel">Ethereum / lending risk<span>Read-only · Free bounded beta</span></span></header>
    {!authenticated&&<nav className="instrumentTabs" aria-label="Risk workspace">{tabs.map(([key,label,n])=><button key={key} type="button" aria-current={view===key?"page":undefined} className={view===key?"selected":""} onClick={()=>{setView(key);setError("")}}><small>{n}</small>{label}</button>)}</nav>}
    {demoOnly?<section className="lookupBar demoBoundary" aria-label="Educational demo"><p>Educational demonstration only. Every balance and scenario here is hypothetical. Live wallet analysis requires a free verified account.</p><button className="button" type="button" onClick={sample}>Explore a hypothetical sample</button><Link className="textButton" href="/signup">Create a free account →</Link></section>:<section className="lookupBar" aria-label="Wallet inspection"><form onSubmit={inspect}><label className="field">Coverage<select aria-label="Protocol coverage" value={coverage} disabled={loading} onChange={e=>{setCoverage(e.target.value);reset();c.setSnapshot(null)}}><option value="aave">Aave V3 normal mode</option><option value="morpho-wbtc">Morpho WBTC/USDC · 86% LLTV</option><option value="combined">Aave + bounded Morpho market</option></select></label><label htmlFor="wallet-address">Public Ethereum address</label><div className="lookupControls"><input id="wallet-address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="0x…" autoComplete="off" spellCheck={false} maxLength={42}/><button className="button" disabled={loading} type="submit">{loading?"Reading evidence…":"Inspect wallet"}<span aria-hidden="true">↗</span></button></div></form><div className="lookupSecondary"><button className="textButton" type="button" onClick={sample}>Explore a hypothetical sample</button><button className="textButton" type="button" onClick={connect}>Connect read-only wallet</button></div></section>}
    {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}
    {s&&<div className={`evidenceStrip ${s.sample?"sample":""}`}><strong>{s.sample?"HYPOTHETICAL SAMPLE · NOT LIVE":stale?"STALE SNAPSHOT":s.status==="READY"?"ON-CHAIN SNAPSHOT":"UNSUPPORTED MODEL"}</strong><span>{s.sample?"Invented educational inputs":`Block ${s.blockNumber} · ${new Date(s.blockTimestamp*1000).toLocaleTimeString()} · Ethereum`}</span>{!s.sample&&<button className="textButton" type="button" disabled={loading} onClick={refresh}>{loading?"Refreshing…":"Refresh evidence ↻"}</button>}</div>}
    {s?.warnings?.map((w,i)=><div className="warning" key={i}>{w}</div>)}{stale&&<div className="warning">This snapshot is older than three minutes. Scenario and action calculations are withheld until refreshed.</div>}
    {!s&&view!=="reports"?<section className="emptyInstrument"><div className="largeIndex">{tabs.find(t=>t[0]===view)?.[2]}</div><div><div className="eyebrow">BEGIN WITH A POSITION</div><h2>Your exposure, in perspective.</h2><p>Inspect a public Ethereum address to discover lending exposure within your selected protocol coverage. Or learn the full scenario and Defense Frontier workflow with a clearly labeled hypothetical portfolio.</p><p className="muted">No custody. No signing. No fabricated live results.</p></div></section>:<>
      {view==="portfolio"&&s&&<>
        <section className="metricRibbon" aria-label="Observed portfolio metrics"><div><span>Collateral value</span><strong>{money(s.observedCollateralRaw)}</strong><small>Validated price references / USD</small></div><div><span>Borrowing exposure</span><strong>{money(s.observedDebtRaw)}</strong><small>Debt accrued at the block</small></div><div><span>{s.model==="ethereum-lending-1"?"Minimum modeled health":"Observed health factor"}</span><strong>{hf(s.observedHealthFactorRaw)}</strong><small>Liquidation eligibility below 1.000</small></div><div><span>Native gas balance</span><strong>{tokenAmount(s.nativeBalanceRaw,18,4)} <em>ETH</em></strong><small>Public wallet balance</small></div></section>
        <section className="instrumentPanel"><div className="sectionHeading"><div><div className="eyebrow">LIQUIDATIONGUARD</div><h2>Lending exposure</h2></div><button className="textButton" type="button" onClick={()=>setView("scenarios")}>Stress-test this position →</button></div>{!reserves.length?<p>No open lending position was found within the selected coverage at this block. This does not imply that the wallet has no exposure on other protocols or chains.</p>:<div className="tableScroll"><table><thead><tr><th>Protocol / asset</th><th>Supplied</th><th>Borrowed</th><th>Oracle price</th><th>Liquidation threshold</th><th>Evidence</th></tr></thead><tbody>{s.positions.flatMap(p=>p.reserves.map(r=><tr key={`${p.id}:${r.asset}`}><td><b>{r.symbol}</b><small>{p.protocol}</small><small>{r.collateralEnabled?"Collateral enabled":"Not collateral"}</small></td><td>{tokenAmount(r.collateralRaw,r.decimals)}</td><td>{tokenAmount(r.debtRaw,r.decimals)}</td><td>{oraclePrice(r.priceRaw)}</td><td>{(Number(r.ltBps)/100).toFixed(2)}%</td><td>{r.oracleState}</td></tr>))}</tbody></table></div>}</section>
        <div className="twoColumns"><section className="instrumentPanel"><div className="eyebrow">CAPITAL, WITH CONTEXT</div><h2>See what changes the outcome.</h2><p>Debt repayment and collateral supply have different effects on stressed health. Compare them against your own budget and target.</p><button className="button" type="button" onClick={()=>setView("frontier")}>Open Defense Frontier →</button></section><section className="instrumentPanel"><div className="eyebrow">COVERAGE BOUNDARY</div><h2>Know what is supported.</h2><p>Ethereum Aave V3 normal mode and one Morpho WBTC/USDC market at 86% LLTV. Other Morpho markets, eMode, isolation, chains and unvalidated oracle sources remain unsupported.</p><Link className="textButton" href="/methodology">Read the methodology ↗</Link></section></div>
      </>}
      {view==="scenarios"&&s&&<>
        <section className="instrumentPanel"><div className="sectionHeading"><div><div className="eyebrow">DETERMINISTIC STRESS TEST</div><h2>Define the market you want to test.</h2></div><button className="textButton" onClick={()=>{c.setShocks({});c.setResult(null)}} type="button">Reset scenario</button></div><p>A shock affects every collateral and debt balance denominated in that token. These are user assumptions, not forecasts.</p><div className="scenarioGrid">{uniqueReserves.map(r=><label className="shockControl" key={r.asset}><span>{r.symbol} price shock <strong>{(c.shocks[r.asset.toLowerCase()]??0)/100}%</strong></span><input aria-label={`${r.symbol} price shock`} type="range" min="-9500" max="10000" step="100" value={c.shocks[r.asset.toLowerCase()]??0} disabled={!ready} onChange={e=>{c.setShocks({...c.shocks,[r.asset.toLowerCase()]:Number(e.target.value)});c.setResult(null)}}/><span className="rangeLabels"><small>−95%</small><small>Unchanged</small><small>+100%</small></span></label>)}</div></section>
        <section className="instrumentPanel"><div className="eyebrow">BEFORE / UNDER YOUR SCENARIO</div><h2>Position risk, without netting.</h2>{s.positions.map((p,i)=>{const base=metrics(p),o=outcomes[i];return <div className="scenarioResult" key={p.id}><div><span>{p.protocol} / Ethereum</span><h3>Health factor</h3><strong>{hf(base.healthFactorRaw)} <span aria-hidden="true">→</span> {o?hf(o.healthFactorRaw):"Withheld"}</strong></div><div><span>Stressed collateral</span><strong>{o?money(o.collateralRaw):"—"}</strong></div><div><span>Stressed debt</span><strong>{o?money(o.debtRaw):"—"}</strong></div><div className={o?.liquidatable?"dangerText":""}>{o?.liquidatable?"Below modeled liquidation threshold":o?"Liquidation threshold not crossed in this scenario":"Supported fresh evidence required"}</div></div>})}<button className="button" type="button" onClick={()=>setView("frontier")}>Compare defensive alternatives →</button></section>
      </>}
      {view==="frontier"&&s&&<>
        <section className="frontierIntro"><div className="eyebrow">THE RIVEXIS DEFENSE FRONTIER</div><h2>What can your capital change?</h2><p>Compare balance-constrained repayment and collateral alternatives under your chosen scenario. Every result retains its costs, assumptions and remaining modeled risk.</p></section>
        <section className="instrumentPanel"><form className="constraintForm" onSubmit={e=>{e.preventDefault();compare()}}><label className="field">Capital budget / USD<input value={c.budget} onChange={e=>{c.setBudget(e.target.value);c.setResult(null)}} inputMode="decimal" required/></label><label className="field">Target health factor<input value={c.target} onChange={e=>{c.setTarget(e.target.value);c.setResult(null)}} inputMode="decimal" required/></label><label className="field">Assumed total fee reserve / USD<input value={c.fee} onChange={e=>{c.setFee(e.target.value);c.setResult(null)}} inputMode="decimal" required/></label><label className="field">Risk objective<select value={c.objective} onChange={e=>{c.setObjective(e.target.value);c.setResult(null)}}><option value="target">Least capital found to reach target</option><option value="max-min">Highest minimum health factor found</option></select></label><button className="button" disabled={!ready} type="submit">Calculate alternatives ↗</button></form><p className="muted">Current price shocks: {uniqueReserves.map(r=>`${r.symbol} ${(c.shocks[r.asset.toLowerCase()]??0)/100}%`).join(" · ")||"None"}. <button className="textButton" type="button" onClick={()=>setView("scenarios")}>Edit scenario</button></p><p className="muted">Only existing eligible wallet balances are allocated. No hypothetical purchases or swaps. The fee reserve is your assumption; execution requires GasGuard.</p></section>
        {c.result&&ready&&<><div className="sectionHeading"><div><div className="eyebrow">{c.result.examined} ALLOCATIONS EXAMINED</div><h2>{c.result.meetsTarget?"Target-reaching alternatives found.":"No alternative found that reaches your target."}</h2></div><button className="ghost" type="button" onClick={()=>download(receipt(),"rivexis-risk-receipt.json")}>Export evidence</button></div><FrontierChart result={c.result}/><div className="frontierResults">{c.result.alternatives.map((a,i)=><article className="alternative" key={i}><div className="alternativeRank">{String(i+1).padStart(2,"0")}<span>{a.actions.length?"MODELED ONLY":"CURRENT STATE"}</span></div><div className="alternativeBody"><h3>{a.actions.length?a.actions.map(x=>`${x.kind==="repay"?"Repay":"Supply"} ${format(x.amountRaw,x.decimals,4)} ${x.symbol}`).join(" + "):"Keep current position (no transaction)"}</h3><p>{a.meetsTarget?"Meets the selected modeled target":"Target remains unmet"} · {a.uncovered} positions below target</p><div className="alternativeMetrics"><div><span>Capital + assumed fees</span><b>{money(a.totalBudgetRaw)}</b></div><div><span>Minimum stressed health</span><b>{hf(a.minHealthFactorRaw)}</b></div><div><span>Execution</span><b>{a.actions.length?"Not simulated":"No transaction"}</b></div></div>{a.actions.some(x=>x.approvalRequired)&&<small className="warningText">Separate token approval required; fees may exceed your assumed reserve.</small>}</div><button className="textButton" type="button" disabled={!!s.sample||a.actions.length!==1} onClick={()=>{const x=a.actions[0];setKind(x.kind);setPositionId(x.positionId);setShares(x.sharesRaw);setAsset(x.asset);setAmount(format(x.amountRaw,x.decimals,x.decimals));setView("transactions");setPreview(null)}}>{!a.actions.length?"No transaction required":s.sample?"Sample only":a.actions.length>1?"Preview each action separately":"Preview action →"}</button></article>)}</div>{!c.result.alternatives.length&&<div className="warning">No eligible balance-constrained action was found. Wallet balances, collateral eligibility or the available budget prevent a supported alternative.</div>}<p className="muted">{c.result.method}</p>{c.result.warnings.map(w=><p className="muted" key={w}>{w}</p>)}</>}
      </>}
      {view==="transactions"&&s&&<>
        <section className="instrumentPanel"><div className="eyebrow">GASGUARD / PRE-EXECUTION INTELLIGENCE</div><h2>Preview the action. Keep the decision.</h2><p>Read-only RPC calls and gas estimates for supported Aave and bounded Morpho actions. Rivexis never signs or submits the transaction.</p><form className="constraintForm" onSubmit={e=>{e.preventDefault();void transaction()}}><label className="field">Position<select aria-label="Transaction position" value={selectedPosition?.id??""} onChange={e=>{setPositionId(e.target.value);setAsset("");setShares(undefined);setPreview(null)}}>{s.positions.map(p=><option key={p.id} value={p.id}>{p.protocol}{p.protocol==="Morpho Blue"?" · WBTC/USDC 86%":" · Ethereum"}</option>)}</select></label><label className="field">Action<select aria-label="Action" value={kind} onChange={e=>{setKind(e.target.value);setShares(undefined);setPreview(null)}}><option value="repay">{selectedPosition?.protocol==="Morpho Blue"?"Repay loan shares":"Repay variable debt"}</option><option value="supply">Supply existing collateral</option><option value="withdraw">Withdraw collateral</option><option value="borrow">{selectedPosition?.protocol==="Morpho Blue"?"Borrow loan asset":"Borrow variable debt"}</option></select></label><label className="field">Asset<select aria-label="Asset" value={selectedAsset} onChange={e=>{setAsset(e.target.value);setShares(undefined);setPreview(null)}}>{transactionReserves.map(r=><option key={r.asset} value={r.asset}>{r.symbol}</option>)}</select></label><label className="field">Token amount<input value={amount} onChange={e=>{setAmount(e.target.value);setShares(undefined);setPreview(null)}} required inputMode="decimal" placeholder="0.00"/></label><button className="button" disabled={loading||!ready||!!s.sample} type="submit">{loading?"Simulating…":"Preview transaction ↗"}</button></form>{!!s.sample&&<p className="warning">Live RPC simulations are unavailable for hypothetical samples. Inspect a real supported wallet.</p>}</section>
        {preview&&<section className="instrumentPanel" aria-live="polite"><div className="eyebrow">{String(preview.status)}</div><h2>{String(preview.simulation).replaceAll("_"," ")}</h2><div className="metricRibbon"><div><span>Health before</span><strong>{hf((preview.before as Metrics)?.healthFactorRaw)}</strong></div><div><span>Modeled health after</span><strong>{hf((preview.after as Metrics)?.healthFactorRaw)}</strong></div><div><span>Gas units</span><strong>{String(preview.gasRaw??"Unknown")}</strong></div><div><span>Gas fee reserve</span><strong>{typeof preview.feeReserveWei==="string"?`${tokenAmount(preview.feeReserveWei,18,6)} ETH`:"Unknown"}</strong></div></div>{(preview.blockers as string[]).map(b=><div key={b} className="warning">{b}</div>)}{(preview.warnings as string[]).map(w=><p className="muted" key={w}>{w}</p>)}<button className="ghost" type="button" onClick={()=>download(preview,"rivexis-transaction-preview.json")}>Export transaction evidence</button></section>}
      </>}
      {view==="reports"&&<>
        <section className="instrumentPanel"><div className="eyebrow">MONITORING / HISTORY / REPORTS</div><h2>A decision deserves a record.</h2><p>Export a reproducible risk receipt with raw snapshot inputs, scenario assumptions, alternatives and model identity. Account reports are private to their owner, with a 20-report limit.</p><div className="inlineActions"><button className="button" type="button" disabled={demoOnly||!c.result||!ready||loading} onClick={save}>{loading?"Saving…":"Save comparison to account"}</button><button className="ghost" type="button" disabled={!c.result} onClick={()=>download(receipt(),"rivexis-risk-receipt.json")}>Export JSON receipt</button><button className="textButton" type="button" disabled={demoOnly||loading} onClick={loadReports}>Load saved reports</button></div><p className="muted">Live saved reports are recalculated on the server from fresh chain evidence. Educational receipts are labeled hypothetical. No financial state is automatically persisted in your browser.</p></section>
        <section className="instrumentPanel"><h2>Historical evidence & notifications</h2><p>Existing account notifications and historical records are retained. Automated DeFi risk emails and server-side continuous monitoring remain disabled.</p>{authenticated?<Link className="textButton" href="/workspace/history">Review retained historical analyses →</Link>:<Link className="textButton" href="/login">Log in for account history →</Link>}</section>
        <BoundedMonitor/>{reports.length>0&&<section className="instrumentPanel"><h2>Saved comparisons</h2>{reports.map(r=><div className="savedReport" key={r.id}><div><b>{r.id}</b><small>{new Date(r.created_at).toLocaleString()}</small></div><button className="ghost" onClick={()=>download(r.receipt,`rivexis-${r.id}.json`)} type="button">Export</button></div>)}</section>}
      </>}
      {s&&<details className="evidenceDetails"><summary>Evidence, model assumptions & coverage</summary><dl><dt>Model</dt><dd>{s.model}</dd><dt>Snapshot identity</dt><dd>{s.blockHash}</dd><dt>Wallet</dt><dd>{s.wallet}</dd><dt>Provider</dt><dd>{String(s.rpcHost??"Educational fixture")}</dd><dt>Oracle unit</dt><dd>USD / 10⁸ for capital and exposure; native loan units and 10³⁶ relative oracle for Morpho health</dd></dl><p>Aave health factor = collateral × weighted liquidation threshold ÷ debt, with Aave integer rounding. Morpho health = floor(floor(collateral × market oracle / 10³⁶) × LLTV / 10¹⁸) ÷ ceiling share-denominated debt. Separate positions are never netted. Interest is accrued at the snapshot block; future interest, parameter changes and unknown oracle behavior remain outside the model.</p>{Array.isArray(s.limitations)&&s.limitations.map((limit,i)=><p key={i}>{String(limit)}</p>)}<button className="textButton" type="button" onClick={()=>download(s,"rivexis-snapshot.json")}>Export raw snapshot →</button></details>}
    </>}
    <footer className="instrumentFooter"><span>RIVEXIS · Free access, bounded usage.</span><span>Financial modeling only. No guarantee of safety or execution.</span></footer>
  </div></>;
}
