"use client";
import {format,type Frontier} from "../../../supabase/functions/rivexis-api/defi-model.mjs";
export function FrontierChart({result,selected=0,onSelect}:{result:Frontier;selected?:number;onSelect?:(i:number)=>void}){
  const finite=result.alternatives.filter(a=>a.minHealthFactorRaw!==null);
  if(!finite.length)return null;
  const maxCapital=Math.max(1,...finite.map(a=>Number(format(a.totalBudgetRaw)))),maxHf=Math.max(2,Number(format(result.targetRaw,18,6)),...finite.map(a=>Number(format(a.minHealthFactorRaw!,18,6)))),target=Number(format(result.targetRaw,18,6));
  const y=(n:number)=>230-n/maxHf*185;
  return <figure className="frontierChart"><figcaption><strong>Capital / modeled stressed health</strong><span>Numbers identify alternatives below. The dashed line is your target.</span></figcaption><svg viewBox="0 0 720 280" role="group" aria-label="Scatter chart comparing alternative costs with minimum stressed health factor"><g stroke="var(--border)" fill="none"><path d="M65 35V230H675"/><path d="M65 80H675M65 130H675M65 180H675" strokeDasharray="2 6"/></g><path d={`M65 ${y(target)}H675`} stroke="var(--bronze)" strokeDasharray="5 6"/><text x="68" y={y(target)-8} fill="var(--bronze)" fontSize="11">Target {target.toFixed(2)}</text><text x="65" y="22" fill="var(--text-muted)" fontSize="10">MINIMUM HEALTH FACTOR</text><text x="65" y="258" fill="var(--text-muted)" fontSize="10">$0</text><text x="590" y="258" fill="var(--text-muted)" fontSize="10">${maxCapital.toFixed(0)}</text>{result.alternatives.map((a,i)=>a.minHealthFactorRaw===null?null:<g key={i} role="button" tabIndex={0} aria-pressed={i===selected} aria-label={`Select alternative ${i+1}: cost $${format(a.totalBudgetRaw)}, health ${format(a.minHealthFactorRaw!,18,3)}`} onClick={()=>onSelect?.(i)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect?.(i)}}}><circle cx={65+Number(format(a.totalBudgetRaw))/maxCapital*590} cy={y(Number(format(a.minHealthFactorRaw,18,6)))} r={i===selected?9:6} stroke={i===selected?"var(--text)":"none"} strokeWidth="2" fill={a.meetsTarget?"var(--soft)":"var(--warn)"}/><text x={65+Number(format(a.totalBudgetRaw))/maxCapital*590+9} y={y(Number(format(a.minHealthFactorRaw,18,6)))+4} fill="var(--text)" fontSize="10">{i+1}</text><title>Alternative {i+1}: ${format(a.totalBudgetRaw)} / health factor {format(a.minHealthFactorRaw,18,3)}</title></g>)}</svg></figure>;
}
