import Link from "next/link";
import {PublicNav} from "./PublicNav";
import {ProductFooter} from "./ProductPage";
import {AuthActions,FeatureLink} from "./AuthActions";
import {SignatureRiskField} from "./SignatureRiskField";
import {DefenseIllustration} from "./DefenseIllustration";
export function Home(){return <><PublicNav/><main className="institutionalHome" id="main-content">
  <section className="folioHero continuousHero" aria-labelledby="hero-title"><div className="folioHeroCopy"><div className="eyebrow"><span className="folioRule"/> DEFI RISK & DECISION INTELLIGENCE</div><h1 id="hero-title">See the risk<br/>before it becomes<br/><em>the consequence.</em></h1><p className="folioLead">Understand lending exposure. Assess the implications of a transaction. Explore what your available capital could change.</p><AuthActions signupLabel="Create free account"/><Link className="folioExplore" href="#intelligence">Explore the intelligence <span aria-hidden="true">↓</span></Link></div><SignatureRiskField/><div className="folioHeroFoot"><span>Risk. Value. Execution. Analysis.</span><span>FREE VERIFIED ACCOUNT · ETHEREUM / VALIDATED LENDING COVERAGE</span></div></section>
  <section className="claritySection" id="intelligence" aria-labelledby="clarity-title"><div className="sectionMarker"><span>THE DISCIPLINE OF CLARITY</span><span>01 / OBSERVE</span></div><div className="clarityLayout"><div><h2 id="clarity-title">Exposure is connected.<br/><em>Your view should be, too.</em></h2><p>Collateral, borrowing, price changes and proposed transactions influence the same decision. RIVEXIS brings those inputs into one coherent, position-specific workflow.</p></div><div className="exposureLedger"><div><span>Collateral & debt</span><span>Protocol accounting</span></div><div><span>Market scenario</span><span>Your explicit assumptions</span></div><div><span>Available capital</span><span>Real constraints</span></div><div className="ledgerConclusion"><b>One considered decision</b><span>Evidence, with its limits</span></div></div></div></section>
  <section className="liquidationShowcase" aria-labelledby="liquidation-title"><div className="sectionMarker"><span>LIQUIDATIONGUARD</span><span>02 / UNDERSTAND</span></div><div className="showcaseLayout"><div className="showcaseCopy"><h2 id="liquidation-title">A threshold.<br/>A sensitivity.<br/><em>A clearer perspective.</em></h2><p>Observe supported collateral, accrued debt and protocol liquidation conditions at a consistent Ethereum block. Change the scenario and see how each position responds.</p><FeatureLink destination="/workspace">Open LiquidationGuard <span aria-hidden="true">↗</span></FeatureLink><small>Free verified account required for live analysis.</small></div><figure className="thresholdPlate"><figcaption>ILLUSTRATIVE AAVE POSITION / NOT LIVE DATA</figcaption><div className="thresholdHeadline"><span>Baseline health</span><strong>1.333</strong><span aria-hidden="true">→</span><strong>1.066</strong><span>After a 20% collateral price decrease</span></div><div className="thresholdScale"><div className="thresholdScaleFill"/><span className="thresholdBoundary"/><span className="thresholdCurrent"/></div><div className="thresholdScaleLabels"><span>Below threshold</span><span>HF = 1.000</span><span>Baseline</span></div><p>10 WETH × $3,000 × 80% ÷ $18,000 debt.<br/>The scenario changes collateral price; debt stays constant.</p><div className="evidenceLine"><span>Protocol-specific rounding</span><span>Fresh oracle checks</span><span>Visible unsupported states</span></div></figure></div></section>
  <section className="gasShowcase" aria-labelledby="gas-title"><div className="sectionMarker"><span>GASGUARD</span><span>03 / ASSESS</span></div><div className="gasEditorial"><div><h2 id="gas-title">Before the transaction,<br/><em>understand the implications.</em></h2><p>A fee is one part of the picture. Review supported calls, balances, allowances and modeled effects on existing positions before choosing your own next step.</p></div><FeatureLink destination="/workspace/transactions">Open GasGuard <span aria-hidden="true">↗</span></FeatureLink></div><ol className="transactionSequence" aria-label="Supported transaction assessment workflow"><li><span>01</span><h3>Proposed action</h3><p>Repay, supply, withdraw or borrow within validated coverage.</p></li><li><span>02</span><h3>Check constraints</h3><p>Token balance, allowance and native ETH needed for fees.</p></li><li><span>03</span><h3>Read-only preview</h3><p>Contract call and gas estimation at the observed block.</p></li><li><span>04</span><h3>Position effects</h3><p>Protocol-specific before-and-after modeled exposure.</p></li></ol><p className="showcaseLimit">Workflow illustration, not a simulation result. No signing or submission. Future fees and execution can differ.</p></section>
  <section className="defenseShowcase" aria-labelledby="defense-title"><div className="sectionMarker"><span>THE RIVEXIS DEFENSE FRONTIER</span><span>04 / COMPARE</span></div><div className="defenseLayout"><div><span className="eyebrow">CAPITAL-CONSTRAINED DEFENSE PLANNING</span><h2 id="defense-title">Knowing the risk<br/>is a starting point.<br/><em>Explore the response.</em></h2><p>Compare feasible repayments and collateral additions against your chosen scenario, capital budget, available balances and risk objective. Review the remaining modeled risk alongside the cost.</p><FeatureLink destination="/workspace/frontier">Explore Defense Frontier <span aria-hidden="true">↗</span></FeatureLink><small>Bounded alternatives, reproducible assumptions. No global-optimum or safety guarantee.</small></div><DefenseIllustration/></div></section>
  <section className="methodologyFolio" aria-labelledby="methodology-title"><div className="sectionMarker"><span>RESEARCH & METHODOLOGY</span><span>EVIDENCE BEFORE EXECUTION</span></div><div className="methodologyIntro"><h2 id="methodology-title">Every number has<br/><em>a path back to evidence.</em></h2><p>Credibility comes from showing the inputs, the accounting and the limits. Inspect the methodology before interpreting a result.</p></div><div className="methodologySteps"><article><span>01 / Source</span><h3>Read the contracts.</h3><p>Balances, configuration and oracle inputs are observed at a pinned block.</p></article><article><span>02 / Validate</span><h3>Check the evidence.</h3><p>Protocol identity, feed freshness, units and block consistency must agree.</p></article><article><span>03 / Model</span><h3>Respect the accounting.</h3><p>Fixed-point arithmetic and protocol-specific rounding define the scenarios.</p></article><article><span>04 / Interpret</span><h3>Keep the limits visible.</h3><p>Unsupported modes, assumptions and execution uncertainty stay explicit.</p></article></div><div className="methodologyFoot"><Link className="textButton" href="/methodology">Read the methodology →</Link><Link className="textButton" href="/demo">Explore an educational demo →</Link></div></section>
  <section className="folioClosing"><span className="eyebrow">RISK. VALUE. EXECUTION. ANALYSIS.</span><h2>Better decisions begin<br/>with <em>clearer intelligence.</em></h2><p>Your assets stay under your control.<br/>Your decision stays yours.</p><AuthActions signupLabel="Create free account"/></section>
</main><ProductFooter/></>}
