import type {LiquidationAnalysis} from "../../../supabase/functions/rivexis-api/defi-liquidation.mjs";
import {format} from "../../../supabase/functions/rivexis-api/defi-model.mjs";
export function percentage(raw:string|null|undefined){if(raw===null||raw===undefined)return 'Not applicable';const v=BigInt(raw),n=v<0n?-v:v;return `${v<0n?'−':''}${n/100n}.${(n%100n).toString().padStart(2,'0')}%`;}
const states:Record<string,string>={NO_DEBT:'No debt',NO_DOWNWARD_TRIGGER:'No downward trigger with other prices fixed',SAME_ASSET_DEBT_UNVALIDATED:'Same-token debt path not validated',NO_COLLATERAL:'No collateral',ZERO_SCENARIO_PRICE:'Scenario price is zero',OUTSIDE_BOUNDED_SEARCH:'Outside the bounded price search'};
const price=(v?:string)=>v?`$${format(v,8,4)}`:'Not available';
export function LiquidationBoundaries({analysis,scenario=false}:{analysis:LiquidationAnalysis;scenario?:boolean}){
 return <section className="instrumentPanel boundaryPanel"><div className="sectionHeading"><div><div className="eyebrow">LIQUIDATIONGUARD / CONDITIONAL BOUNDARIES</div><h2>{scenario?'Thresholds under your scenario':'Distance to the boundary'}</h2></div><span className="modeLabel">Block {analysis.blockNumber}</span></div>
  {analysis.closest?<p className="boundarySummary"><strong>{analysis.closest.protocol} · {analysis.closest.symbol}</strong><span>{percentage(analysis.closest.distanceBps)} to its conditional collateral threshold</span></p>:<p>No validated conditional collateral trigger is available for these positions.</p>}
  <p className="muted">Each row changes one collateral reference price while holding the stated debt, other prices and protocol parameters fixed. This is not a forecast of which asset moves first.</p>
  <div className="tableScroll"><table><caption className="sr-only">Conditional collateral price thresholds in separate liquidation domains</caption><thead><tr><th>Position / collateral</th><th>Current reference</th><th>Threshold reference</th><th>Distance</th><th>Evidence / assumptions</th></tr></thead><tbody>{analysis.rows.map(r=><tr key={`${r.positionId}:${r.asset}`}><td><b>{r.symbol}</b><small>{r.protocol}</small>{r.liquidatable&&<small className="dangerText">Already below modeled boundary</small>}</td><td>{price(r.currentPriceRaw)}</td><td>{r.state==='AVAILABLE'?<>{price(r.minimumHealthyPriceRaw)}<small>{r.protocol==='Morpho Blue'?'Proportional USD estimate':'Minimum healthy oracle reference'}</small></>:states[r.state]??r.state}</td><td>{percentage(r.distanceBps)}</td><td><details><summary>Inspect boundary evidence</summary><p>{r.reason??states[r.state]}</p><dl>{r.firstLiquidatablePriceRaw&&<><dt>First liquidatable USD raw / 10⁸</dt><dd>{r.firstLiquidatablePriceRaw}</dd></>}{r.oracleBoundaryRaw&&<><dt>Minimum healthy relative oracle / 10³⁶</dt><dd>{r.oracleBoundaryRaw}</dd><dt>First liquidatable oracle unit</dt><dd>{r.firstLiquidatableOracleRaw}</dd></>}<dt>Snapshot hash</dt><dd>{analysis.blockHash}</dd></dl></details></td></tr>)}</tbody></table></div>
  <div className="exposureBreakdown"><h3>Concentration by asset</h3>{analysis.exposures.map(e=><div key={e.asset}><b>{e.symbol}</b><span>Collateral {percentage(e.collateralBps)}</span><span>Debt {percentage(e.debtBps)}</span></div>)}</div>
  <details><summary>Boundary methodology and limits</summary>{analysis.limitations.map(x=><p className="muted" key={x}>{x}</p>)}</details>
 </section>;
}
