import type {Frontier} from "../../../supabase/functions/rivexis-api/defi-model.mjs";
import {format} from "../../../supabase/functions/rivexis-api/defi-model.mjs";
const health=(v:string|null)=>v===null?'No debt':format(v,18,3);
export function PlanComparison({result,index,onSelect}:{result:Frontier;index:number;onSelect:(i:number)=>void}){
 const alternative=result.alternatives[index];if(!alternative)return null;
 return <section className="instrumentPanel planComparison" aria-label="Selected defense plan comparison"><div className="sectionHeading"><div><div className="eyebrow">BEFORE → ALTERNATIVE → MODELED OUTCOME</div><h2>Inspect alternative {index+1}</h2></div><label className="field">Alternative<select aria-label="Alternative" value={index} onChange={e=>onSelect(Number(e.target.value))}>{result.alternatives.map((a,i)=><option key={i} value={i}>Alternative {i+1} · ${format(a.totalBudgetRaw)} · {a.meetsTarget?'Target reached':'Target unmet'}</option>)}</select></label></div>
  <div className="planSteps"><div><span>Before / under your scenario</span>{result.baseline.map(o=><p key={o.positionId}><strong>{health(o.healthFactorRaw)}</strong><small>{o.positionId?.startsWith('morpho')?'Morpho Blue':'Aave V3'} · Health factor</small></p>)}</div><div><span>Alternative / modeled action</span>{alternative.actions.length?alternative.actions.map((a,i)=><p key={i}><strong>{a.kind==='repay'?'Repay':'Supply'} {format(a.amountRaw,a.decimals,4)} {a.symbol}</strong><small>{a.approvalRequired?'Separate approval required':'Allowance prerequisite covered at snapshot'}</small></p>):<p>Keep the current position</p>}<p className="muted">Capital ${format(alternative.capitalRaw)} · Assumed fees ${format(alternative.feeReserveRaw)}</p></div><div><span>After / modeled outcome</span>{alternative.outcomes.map(o=><p key={o.positionId}><strong>{health(o.healthFactorRaw)}</strong><small>{o.positionId?.startsWith('morpho')?'Morpho Blue':'Aave V3'} · {o.liquidatable?'Below liquidation threshold':'Threshold not crossed'}</small></p>)}</div></div><p className="muted">{alternative.meetsTarget?'Meets the selected modeled target.':'The selected target remains unmet.'} Execution and total approval costs require separate checks. Independent positions are never netted.</p>
 </section>;
}
