import Link from "next/link";
import {PublicNav} from "./PublicNav";
import {Brand} from "./Brand";
const topics={
  platform:{eyebrow:"ONE COHERENT RISK WORKFLOW",title:"From exposure to a considered decision.",body:"Inspect supported lending positions, define explicit market scenarios, compare balance-constrained alternatives and preview supported transactions in one shared financial context.",sections:[["LiquidationGuard","Aave V3 balances, debt, oracle valuations and liquidation parameters at a single Ethereum block."],["Risk Scenario Lab","User-defined price shocks affect both collateral and debt denominated in the asset. Deterministic scenarios are not market forecasts."],["Defense Frontier","Compare repayments and existing collateral additions against your budget, target and available balances."],["GasGuard","Read-only eth_call and gas estimation, balance and allowance checks, and modeled health-factor effects."]]},
  liquidation:{eyebrow:"LIQUIDATIONGUARD",title:"Know the position. Understand the exposure.",body:"Observe real Ethereum Aave V3 account data and inspect the inputs behind its health factor. Supported normal-mode positions can be stressed through the same fixed-point accounting model.",sections:[["Evidence at one block","Reserve balances, accrued debt, configuration, oracle prices and wallet balances are pinned to one block. The block hash is checked again before returning evidence."],["A clear coverage boundary","eMode, isolation and unvalidated oracle sources remain observable but are withheld from scenario modeling. Morpho and other chains remain unsupported until validated."],["Freshness matters","Snapshots older than three minutes are withheld from new calculations. Supported feed timestamps are checked; a successful RPC read alone cannot establish oracle correctness."]]},
  gas:{eyebrow:"GASGUARD",title:"See the implications before execution.",body:"Preview supported Aave supply, variable repayment, withdrawal and borrowing actions. Compare the modeled position effect with read-only transaction checks and current gas estimates.",sections:[["Separate evidence from simulation","Balance and allowance are observed at the snapshot block. eth_call and eth_estimateGas test the proposed call. Fees remain estimates."],["No hidden execution","RIVEXIS never asks for private keys, signs transactions or submits an action. Approval prerequisites, insufficient balances and RPC failures remain visible."],["What remains uncertain","Simulation does not guarantee inclusion or success. Multi-step approvals, swaps, arbitrary contract traces and MEV protection are not certified."]]},
  frontier:{eyebrow:"THE RIVEXIS DEFENSE FRONTIER",title:"A clearer view of what your capital can change.",body:"Given supported positions, a user-defined market scenario, a capital budget and a risk objective, compare feasible modeled repayments and collateral alternatives with reproducible evidence.",sections:[["Constraints before rankings","Available wallet token balances are shared across alternatives. Capital and the assumed fee reserve cannot exceed the chosen budget."],["Transparent bounded search","The beta examines 5% budget increments and at most two actions per alternative. It reports the least capital or highest minimum health found within that search, without claiming a global optimum."],["Risk stays position-specific","Independent positions cannot protect each other through accounting netting. Remaining positions below target stay visible. Live discovery currently covers one Aave account; multi-position model tests are not multi-protocol production coverage."],["Model feasibility is not execution","Options remain MODELED ONLY until a fresh supported transaction preview. Approvals, caps, liquidity and changing protocol conditions can prevent execution."]]},
  methodology:{eyebrow:"RESEARCH & METHODOLOGY",title:"Every number has a path back to evidence.",body:"One canonical model connects protocol accounting, deterministic scenarios, defensive alternatives and transaction effects. Raw integer values and calculation assumptions stay exportable.",sections:[["Protocol semantics","Aave normal-mode collateral values use token decimals and oracle USD units. Weighted liquidation thresholds and health factors follow protocol integer rounding. Debt balances incorporate accrued interest at the observed block."],["Reproducible receipts","JSON exports retain wallet and contract identities, block number and hash, raw balances, oracle sources, scenario constraints, examined alternatives and model identity."],["Uncertainty remains explicit","Missing, stale, unvalidated or inconsistent inputs disable modeling. Ethereum Aave V3 WETH, USDC and USDT timestamp adapters are prioritized. Other oracle wrappers require separate validation."],["Financial boundaries","No forecast, personalized licensed investment advice, guaranteed protection or liquidation timing is offered. A model result covers only the supported assumptions."]]},
  security:{eyebrow:"SECURITY & PRIVACY",title:"Read-only by design. Accountable by default.",body:"RIVEXIS observes public wallet information and models user-selected actions. Assets remain under your control. Account identity and historical records stay on the existing infrastructure.",sections:[["Wallet permissions","Paste an address without authentication. Optional browser-wallet access requests an address only. No private keys, seed phrases or signing permissions are requested."],["Account protection","Existing Supabase authentication, HttpOnly secure sessions, CSRF controls and server-side ownership checks are retained. Privileged keys remain on the server."],["Data and retention","Financial state is not automatically stored in the browser. Account reports are explicitly saved, owner-scoped and capped at 20. Public RPC providers see queried addresses; exported receipts contain public financial information."],["Known security findings","The current Supabase advisor reports pg_net in the public schema and disabled leaked-password protection. Legacy tables lack RLS but have no anon/authenticated table grants. The build toolchain has one documented dependency advisory. These findings are retained in release evidence."]]},
  docs:{eyebrow:"DOCUMENTATION",title:"Start with evidence. Move at your own pace.",body:"Public analysis is free and requires no account. Create an account only for owner-scoped saved reports and retained historical records.",sections:[["1 / Inspect","Open the app, paste an Ethereum address and inspect wallet evidence. A hypothetical sample is available to learn the workflow, clearly labeled throughout."],["2 / Stress-test","Adjust asset price shocks. Review each position's modeled health, collateral and debt. Refresh if the snapshot becomes stale."],["3 / Compare","Choose a capital budget, target health factor, fee reserve assumption and objective. Compare the supported bounded alternatives; review unmet targets and remaining risks."],["4 / Preview and preserve","Preview one supported live action with GasGuard. Export the raw snapshot or risk receipt. Account reports are recalculated from fresh server evidence."],["Beta limits","300 RPC-backed requests daily across the beta, four per wallet per minute, 80 reserves per discovery and 20 saved reports per account. No continuous DeFi polling or paid AI dependency."]]},
  about:{eyebrow:"RISK. VALUE. EXECUTION. ANALYSIS.",title:"Financial precision. A more considered decision.",body:"RIVEXIS is a non-custodial DeFi Risk & Decision Intelligence platform for self-directed borrowers and advanced digital-asset users.",sections:[["Our purpose","Understand your exposure. Explore what could happen. Compare supported alternatives under your own constraints."],["Our discipline","Evidence-driven computation, protocol-specific semantics, clear limitations and deliberate usability. No fabricated live balances or opaque safety score."]]},
} as const;
export type Topic=keyof typeof topics;
export function ProductPage({topic}:{topic:Topic}){const t=topics[topic];return <><PublicNav/><main className="researchPage"><div className="eyebrow">{t.eyebrow}</div><h1>{t.title}</h1><p className="researchLead">{t.body}</p><Link className="button" href="/app">Explore the workspace ↗</Link><div className="researchSections">{t.sections.map(([title,body],i)=><section key={title}><span className="editorialNumber">{String(i+1).padStart(2,"0")}</span><div><h2>{title}</h2><p>{body}</p></div></section>)}</div></main><ProductFooter/></>}
export function ProductFooter(){return <footer className="productFooter"><div><Brand/><p>Risk. Value. Execution. Analysis.</p><small>Financial modeling only. No custody or automatic execution.</small></div><nav aria-label="Footer"><Link href="/methodology">Methodology</Link><Link href="/security">Security & privacy</Link><Link href="/docs">Documentation</Link><Link href="/about">About RIVEXIS</Link></nav></footer>}

