"""Author SVG masters from local font outlines and the original interlaced-X concept.
Authoring dependency: fonttools==4.66.1. Fonts are not redistributed.
Usage: python scripts/generate-brand.py --serif /path/to/timesbd.ttf --sans /path/to/arial.ttf
"""
import argparse,json
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.basePen import BasePen
from fontTools.svgLib.path import parse_path
parser=argparse.ArgumentParser();parser.add_argument('--serif',required=True);parser.add_argument('--sans',required=True)
args=parser.parse_args();root=Path(__file__).resolve().parents[1]
serif=TTFont(args.serif);sans=TTFont(args.sans)
def outline(font,text,x,y,scale,tracking):
    paths=[];glyphs=font.getGlyphSet();cmap=font.getBestCmap()
    for char in text:
        if char!=' ':
            glyph=glyphs[cmap[ord(char)]];pen=SVGPathPen(glyphs)
            glyph.draw(TransformPen(pen,(scale,0,0,-scale,x,y)))
            paths.append(pen.getCommands())
            x+=glyph.width*scale+tracking
        else:x+=font['hmtx'].metrics[cmap[ord(' ')]][0]*scale+tracking
    return ''.join(paths),x
left,x=outline(serif,'RIVE',18,129,.08,14)
markX=x+2
right,end=outline(serif,'IS',markX+120+16,129,.08,14)
width=round(end+4);word=left+right
# Two crossing ribbons; the separate centre bridge makes the weave legible
# without bevels, gradients, or raster content. Geometry is hand-authored.
ribbons=['M8 4H36L72 45Q88 63 72 82L38 122H8L51 73Q60 63 51 53Z',
         'M84 4H112L69 53Q60 63 69 73L112 122H84L48 82Q32 63 48 45Z']
bridge='M54 42C39 54 45 66 57 75C65 81 65 86 57 93L65 93C79 81 69 69 61 63C53 57 53 51 62 42Z'
_,tagwidth=outline(sans,'RISK. VALUE. EXECUTION. ANALYSIS.',0,0,.016,2.0)
tag,_=outline(sans,'RISK. VALUE. EXECUTION. ANALYSIS.',(width-tagwidth)/2,181,.016,2.0)
out=root/'apps/web/public/brand';out.mkdir(parents=True,exist_ok=True)
def content(ink,accent,lockup=False):
    return f'<path fill="{ink}" d="{word}"/><g transform="translate({markX} 4)"><path fill="{accent}" d="{ribbons[0]}"/><path fill="{accent}" d="{ribbons[1]}"/><path fill="{ink}" d="{bridge}"/></g>'+ (f'<path fill="{ink}" opacity=".82" d="{tag}"/>' if lockup else '')
def svg(body,w=width,h=146):return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" role="img" aria-label="RIVEXIS">{body}</svg>'
for variant,ink,accent in [('dark','#E9EBE7','#80AAA1'),('light','#202B2D','#326C6A'),('ivory','#E9EBE7','#E9EBE7'),('graphite','#202B2D','#202B2D')]:
    for lockup in [False,True]:
        name='lockup' if lockup else 'wordmark'
        (out/f'rivexis-{name}-{variant}.svg').write_text(svg(content(ink,accent,lockup),h=203 if lockup else 146),encoding='utf-8')
# Symbol-only exports have enough negative space to survive 16px rendering.
icon=f'<g transform="translate(20 17)"><path fill="#80AAA1" d="{ribbons[0]}"/><path fill="#80AAA1" d="{ribbons[1]}"/><path fill="#E9EBE7" d="{bridge}"/></g>'
(out/'rivexis-symbol.svg').write_text(svg('<rect width="160" height="160" rx="28" fill="#141B1D"/>'+icon,160,160),encoding='utf-8')
(out/'rivexis-symbol-transparent.svg').write_text(svg(icon,160,160),encoding='utf-8')
(out/'rivexis-compact.svg').write_text(svg(icon,160,160),encoding='utf-8')
(out/'rivexis-report-header.svg').write_text(svg(content('#202B2D','#326C6A',True),h=203),encoding='utf-8')
geometry={'width':width,'wordmark':word,'tagline':tag,'markX':markX,'ribbons':ribbons,'bridge':bridge}
(root/'apps/web/components/brand-geometry.ts').write_text('// Generated by scripts/generate-brand.py; original identity, vector paths only.\nexport const brandGeometry='+json.dumps(geometry,separators=(',',':'))+' as const;\n',encoding='utf-8')
class PdfPen(BasePen):
    def __init__(self):super().__init__(None);self.commands=[]
    def point(self,p):return ' '.join(f'{n:.5f}'.rstrip('0').rstrip('.') for n in p)
    def _moveTo(self,p):self.commands.append(self.point(p)+' m')
    def _lineTo(self,p):self.commands.append(self.point(p)+' l')
    def _curveToOne(self,a,b,c):self.commands.append(' '.join(self.point(p) for p in [a,b,c])+' c')
    def _closePath(self):self.commands.append('h')
    def _endPath(self):pass
def pdf_path(path):
    pen=PdfPen();parse_path(path,pen);return '\n'.join(pen.commands)+'\nf'
pdf='q\n0.21 0 0 -0.21 72 768 cm\n0.12549 0.16863 0.17647 rg\n'+pdf_path(word)+'\nq\n1 0 0 1 '+str(markX)+' 4 cm\n0.19608 0.42353 0.41569 rg\n'+pdf_path(''.join(ribbons))+'\n0.12549 0.16863 0.17647 rg\n'+pdf_path(bridge)+'\nQ\n'+pdf_path(tag)+'\nQ'
(root/'supabase/functions/rivexis-api/brand.mjs').write_text('// Generated from the same vector master as Brand.tsx. No remote assets or fonts.\nexport const BRAND_REPORT_SVG='+json.dumps(svg(content('#202B2D','#326C6A',True),h=203))+';\nexport const BRAND_PDF_HEADER='+json.dumps(pdf)+';\n',encoding='utf-8')
print(f'Generated vector masters: {width} x 146; outlined lockup {width} x 203.')
