-- Rivexis production schema blueprint (PostgreSQL).
-- Keep provider payloads at adapter boundaries; JSONB is used only where the structure is genuinely provider/engine-variable.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password_hash text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE profiles (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, display_name text, user_role text NOT NULL CHECK (user_role IN ('Individual','Fund','Treasury','Analyst')), onboarding_complete boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organization_members (organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (organization_id,user_id));
CREATE TABLE workspaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id), owner_user_id uuid REFERENCES users(id), name text NOT NULL, role_context text NOT NULL, settings jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX workspaces_owner_idx ON workspaces(owner_user_id);

CREATE TABLE chains (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), chain_id bigint NOT NULL UNIQUE, name text NOT NULL UNIQUE, native_currency text NOT NULL, explorer text, status text NOT NULL, capabilities jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), symbol text NOT NULL, name text NOT NULL, asset_type text NOT NULL, canonical_identifier text UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), asset_id uuid NOT NULL REFERENCES assets(id), chain_id uuid NOT NULL REFERENCES chains(id), contract_address text NOT NULL, decimals int, UNIQUE(chain_id,contract_address));
CREATE TABLE protocols (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text UNIQUE, category text, website text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE contracts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), chain_id uuid NOT NULL REFERENCES chains(id), protocol_id uuid REFERENCES protocols(id), address text NOT NULL, verified boolean, proxy_type text, deployment_block bigint, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(chain_id,address));
CREATE TABLE wallets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, chain_id uuid REFERENCES chains(id), address text NOT NULL, label text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,chain_id,address));
CREATE TABLE wallet_groups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE data_sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider_id text NOT NULL UNIQUE, provider_name text NOT NULL, category text NOT NULL, authority_class text, supported_chains jsonb NOT NULL DEFAULT '[]', supported_engines jsonb NOT NULL DEFAULT '[]', authentication_type text, rate_limit text, commercial_tier text, expected_freshness text, provider_priority int NOT NULL DEFAULT 100, license_notes text, storage_policy text, redistribution_policy text, cache_ttl_seconds int, attribution_required boolean NOT NULL DEFAULT false, enabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE provider_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid REFERENCES workspaces(id), provider_id uuid NOT NULL REFERENCES data_sources(id), status text NOT NULL, credential_reference text, config jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,provider_id));
CREATE TABLE provider_health_checks (id bigserial PRIMARY KEY, provider_id uuid NOT NULL REFERENCES data_sources(id), status text NOT NULL, latency_ms numeric, message text, checked_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX provider_health_provider_time_idx ON provider_health_checks(provider_id,checked_at DESC);
CREATE TABLE provider_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE, provider_id uuid REFERENCES data_sources(id), provider_key text NOT NULL, analysis_id uuid, operation text NOT NULL, endpoint text, status text NOT NULL, latency_ms numeric, estimated_cost numeric, attempts int NOT NULL DEFAULT 0, retries int NOT NULL DEFAULT 0, cache_hit boolean NOT NULL DEFAULT false, request_id_external text, trace_id text, span_id text, observed_at timestamptz, retrieved_at timestamptz NOT NULL DEFAULT now(), error_class text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX provider_requests_workspace_time_idx ON provider_requests(workspace_id,created_at DESC);

CREATE TABLE analyses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid REFERENCES workspaces(id), subject_type text NOT NULL, subject_ref text, status text NOT NULL, role_context text, block_number bigint, chain_id uuid REFERENCES chains(id), data_confidence numeric CHECK (data_confidence BETWEEN 0 AND 100), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX analyses_workspace_time_idx ON analyses(workspace_id,created_at DESC);
CREATE TABLE engine_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, engine_id text NOT NULL, engine_version text NOT NULL, status text NOT NULL, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, duration_ms numeric, UNIQUE(analysis_id,engine_id));
CREATE TABLE engine_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), engine_run_id uuid NOT NULL UNIQUE REFERENCES engine_runs(id) ON DELETE CASCADE, risk_score numeric CHECK (risk_score BETWEEN 0 AND 100), data_confidence numeric CHECK (data_confidence BETWEEN 0 AND 100), engine_confidence numeric CHECK (engine_confidence BETWEEN 0 AND 100), severity text NOT NULL, summary text NOT NULL, metrics jsonb NOT NULL DEFAULT '{}', signals jsonb NOT NULL DEFAULT '[]', warnings jsonb NOT NULL DEFAULT '[]', hard_blockers jsonb NOT NULL DEFAULT '[]', mitigations jsonb NOT NULL DEFAULT '[]', assumptions jsonb NOT NULL DEFAULT '[]', provider_consensus text, calculation_version text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, decision text NOT NULL CHECK (decision IN ('PROCEED','MODIFY','WAIT','AVOID','UNKNOWN')), risk_score numeric CHECK (risk_score BETWEEN 0 AND 100), decision_confidence numeric CHECK (decision_confidence BETWEEN 0 AND 100), data_confidence numeric CHECK (data_confidence BETWEEN 0 AND 100), policy_version text NOT NULL, recommended_action text, safer_option text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE decision_reasons (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), decision_id uuid NOT NULL REFERENCES decisions(id) ON DELETE CASCADE, rank int NOT NULL, reason text NOT NULL, dimension text, material boolean NOT NULL DEFAULT true, UNIQUE(decision_id,rank));
CREATE TABLE findings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, engine_run_id uuid REFERENCES engine_runs(id), finding_type text NOT NULL, severity text, title text NOT NULL, detail text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, engine_run_id uuid REFERENCES engine_runs(id), provider_id uuid REFERENCES data_sources(id), source_type text NOT NULL, provider_endpoint text, provider_request_id text, observed_at timestamptz, retrieved_at timestamptz NOT NULL, block_number bigint, chain_id uuid REFERENCES chains(id), asset_id uuid REFERENCES assets(id), protocol_id uuid REFERENCES protocols(id), raw_reference text, normalized_value jsonb, calculation_version text, engine_version text, confidence numeric CHECK (confidence BETWEEN 0 AND 100), freshness text, license_classification text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX evidence_analysis_idx ON evidence(analysis_id);
CREATE TABLE source_conflicts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id) ON DELETE CASCADE, metric text NOT NULL, source_a uuid REFERENCES data_sources(id), value_a jsonb NOT NULL, source_b uuid REFERENCES data_sources(id), value_b jsonb NOT NULL, difference numeric, difference_percentage numeric, expected_tolerance numeric, severity text, resolution_method text, resolved_value jsonb, resolution_confidence numeric CHECK (resolution_confidence BETWEEN 0 AND 100), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), chain_id uuid NOT NULL REFERENCES chains(id), tx_hash text, from_address text, to_address text, native_value numeric, nonce bigint, gas_limit numeric, gas_price numeric, block_number bigint, observed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(chain_id,tx_hash));
CREATE TABLE transaction_traces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transaction_id uuid NOT NULL REFERENCES transactions(id) ON DELETE CASCADE, trace_index int NOT NULL, call_type text, from_address text, to_address text, value numeric, gas_used numeric, success boolean, revert_reason text, parent_trace_id uuid, UNIQUE(transaction_id,trace_index));
CREATE TABLE transfers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transaction_id uuid REFERENCES transactions(id), chain_id uuid REFERENCES chains(id), asset_id uuid REFERENCES assets(id), from_address text, to_address text, amount numeric NOT NULL, usd_value numeric, observed_at timestamptz, provider_id uuid REFERENCES data_sources(id));
CREATE TABLE simulations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id), transaction_id uuid REFERENCES transactions(id), provider_id uuid REFERENCES data_sources(id), success boolean, revert_reason text, gas_estimate numeric, state_block bigint, result jsonb NOT NULL DEFAULT '{}', observed_at timestamptz, retrieved_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE security_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id), risk_score numeric, severity text, hard_blocker boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE security_signals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assessment_id uuid NOT NULL REFERENCES security_assessments(id) ON DELETE CASCADE, provider_id uuid REFERENCES data_sources(id), signal_type text NOT NULL, severity text, affected_asset uuid REFERENCES assets(id), affected_address text, explanation text, confidence numeric, observed_at timestamptz);

CREATE TABLE monitors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), entity_type text NOT NULL, entity_ref text NOT NULL, rules jsonb NOT NULL DEFAULT '[]', thresholds jsonb NOT NULL DEFAULT '{}', enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE threat_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), monitor_id uuid REFERENCES monitors(id), provider_id uuid REFERENCES data_sources(id), event_type text NOT NULL, severity text NOT NULL, affected_entity text, estimated_exposure numeric, status text NOT NULL, confidence numeric, observed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), threat_event_id uuid REFERENCES threat_events(id), severity text NOT NULL, status text NOT NULL DEFAULT 'open', title text NOT NULL, detail text, acknowledged_at timestamptz, resolved_at timestamptz, occurrence_count int NOT NULL DEFAULT 1, first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), delivery_status text NOT NULL DEFAULT 'pending', delivery_attempts int NOT NULL DEFAULT 0, next_delivery_at timestamptz, last_delivery_error text, delivered_at timestamptz, dead_lettered_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX alerts_delivery_due_idx ON alerts(workspace_id,delivery_status,next_delivery_at);

CREATE TABLE entities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), canonical_name text, entity_type text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE entity_labels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_id uuid REFERENCES entities(id), chain_id uuid REFERENCES chains(id), address text NOT NULL, label text NOT NULL, provider_id uuid REFERENCES data_sources(id), confidence numeric, verified boolean NOT NULL DEFAULT false, observed_at timestamptz, retrieved_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE fund_flows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid REFERENCES analyses(id), from_entity uuid REFERENCES entities(id), to_entity uuid REFERENCES entities(id), asset_id uuid REFERENCES assets(id), amount numeric, usd_value numeric, tx_hash text, observed_at timestamptz, provider_id uuid REFERENCES data_sources(id));

CREATE TABLE routes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid REFERENCES analyses(id), provider_id uuid REFERENCES data_sources(id), source_chain_id uuid REFERENCES chains(id), destination_chain_id uuid REFERENCES chains(id), source_asset_id uuid REFERENCES assets(id), destination_asset_id uuid REFERENCES assets(id), expected_received numeric, total_fee_usd numeric, duration_seconds int, risk_score numeric, recommended boolean NOT NULL DEFAULT false, observed_at timestamptz, retrieved_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE route_steps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), route_id uuid NOT NULL REFERENCES routes(id) ON DELETE CASCADE, step_index int NOT NULL, step_type text NOT NULL, provider_name text, contract_address text, fee_usd numeric, expected_seconds int, metadata jsonb NOT NULL DEFAULT '{}', UNIQUE(route_id,step_index));

CREATE TABLE prices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), asset_id uuid NOT NULL REFERENCES assets(id), provider_id uuid REFERENCES data_sources(id), price numeric NOT NULL, quote_currency text NOT NULL DEFAULT 'USD', observed_at timestamptz NOT NULL, retrieved_at timestamptz NOT NULL, block_number bigint, freshness text, confidence numeric);
CREATE INDEX prices_asset_time_idx ON prices(asset_id,observed_at DESC);
CREATE TABLE oracle_feeds (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), chain_id uuid REFERENCES chains(id), protocol_id uuid REFERENCES protocols(id), asset_id uuid REFERENCES assets(id), oracle_type text NOT NULL, contract_address text, provider_id uuid REFERENCES data_sources(id), metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE oracle_observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), oracle_feed_id uuid NOT NULL REFERENCES oracle_feeds(id), value numeric NOT NULL, observed_at timestamptz NOT NULL, retrieved_at timestamptz NOT NULL, block_number bigint, freshness text);

CREATE TABLE portfolios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), name text NOT NULL, valuation_currency text NOT NULL DEFAULT 'USD', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE portfolio_positions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), portfolio_id uuid NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE, asset_id uuid REFERENCES assets(id), chain_id uuid REFERENCES chains(id), protocol_id uuid REFERENCES protocols(id), quantity numeric NOT NULL, price numeric, value_usd numeric, counterparty text, observed_at timestamptz, source text, UNIQUE(portfolio_id,asset_id,chain_id,protocol_id));
CREATE TABLE protocol_metrics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), protocol_id uuid NOT NULL REFERENCES protocols(id), chain_id uuid REFERENCES chains(id), metric text NOT NULL, value numeric, unit text, provider_id uuid REFERENCES data_sources(id), observed_at timestamptz NOT NULL, retrieved_at timestamptz NOT NULL, methodology text);
CREATE TABLE protocol_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analysis_id uuid NOT NULL REFERENCES analyses(id), protocol_id uuid NOT NULL REFERENCES protocols(id), smart_contract_risk numeric, economic_risk numeric, liquidity_risk numeric, oracle_risk numeric, governance_risk numeric, market_risk numeric, dependency_risk numeric, contagion_risk numeric, overall_risk numeric, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE defi_positions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), protocol_id uuid REFERENCES protocols(id), market text, collateral_asset_id uuid REFERENCES assets(id), collateral_value numeric, debt_asset_id uuid REFERENCES assets(id), debt_value numeric, liquidation_threshold numeric, ltv numeric, health_factor numeric, observed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE yield_strategies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), protocol_id uuid REFERENCES protocols(id), asset_id uuid REFERENCES assets(id), pool_ref text, vault_ref text, base_yield numeric, incentive_yield numeric, lock_period_seconds bigint, observed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE treasury_scenarios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), name text NOT NULL, assumptions jsonb NOT NULL DEFAULT '{}', shocks jsonb NOT NULL DEFAULT '{}', result jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE saved_analyses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), analysis_id uuid NOT NULL REFERENCES analyses(id), name text, tags text[] NOT NULL DEFAULT '{}', archived boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,analysis_id));
CREATE TABLE reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), analysis_id uuid REFERENCES analyses(id), decision_id uuid REFERENCES decisions(id), report_type text, format text NOT NULL, storage_ref text, payload jsonb, status text NOT NULL, approved_by_user_id uuid REFERENCES users(id), approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX reports_workspace_type_status_idx ON reports(workspace_id,report_type,status);
CREATE TABLE user_risk_policies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL UNIQUE REFERENCES workspaces(id), max_overall_risk numeric, maximum_concentration numeric, minimum_liquidity_reserve numeric, allowed_chains jsonb NOT NULL DEFAULT '[]', allowed_protocols jsonb NOT NULL DEFAULT '[]', prohibited_dependencies jsonb NOT NULL DEFAULT '[]', policy jsonb NOT NULL DEFAULT '{}', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notification_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), channel text NOT NULL, severity_threshold text, enabled boolean NOT NULL DEFAULT true, config jsonb NOT NULL DEFAULT '{}', UNIQUE(workspace_id,channel));
CREATE TABLE audit_logs (id bigserial PRIMARY KEY, workspace_id uuid REFERENCES workspaces(id), actor_user_id uuid REFERENCES users(id), action text NOT NULL, entity_type text NOT NULL, entity_id text, request_id text, trace_id text, span_id text, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_logs_workspace_time_idx ON audit_logs(workspace_id,created_at DESC);
CREATE INDEX audit_logs_trace_idx ON audit_logs(workspace_id,trace_id,created_at);
CREATE INDEX provider_requests_trace_idx ON provider_requests(workspace_id,trace_id,created_at);
