"""Promote P3 scaffolds to production-blueprint field and relationship coverage."""
from __future__ import annotations
import hashlib
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

revision="0004_blueprint_contract"
down_revision="0003_production_schema_rls"
branch_labels=None
depends_on=None

EXPECTED_COLUMNS={'alerts': {'acknowledged_at': 'timestamptz',
            'created_at': 'timestamptz',
            'detail': 'text',
            'id': 'uuid',
            'resolved_at': 'timestamptz',
            'severity': 'text',
            'status': 'text',
            'threat_event_id': 'uuid',
            'title': 'text',
            'workspace_id': 'uuid'},
 'analyses': {'block_number': 'bigint',
              'chain_id': 'uuid',
              'created_at': 'timestamptz',
              'data_confidence': 'numeric',
              'id': 'uuid',
              'role_context': 'text',
              'status': 'text',
              'subject_ref': 'text',
              'subject_type': 'text',
              'updated_at': 'timestamptz',
              'workspace_id': 'uuid'},
 'assets': {'asset_type': 'text',
            'canonical_identifier': 'text',
            'created_at': 'timestamptz',
            'id': 'uuid',
            'name': 'text',
            'symbol': 'text',
            'updated_at': 'timestamptz'},
 'audit_logs': {'action': 'text',
                'actor_user_id': 'uuid',
                'created_at': 'timestamptz',
                'detail': 'jsonb',
                'entity_id': 'text',
                'entity_type': 'text',
                'id': 'bigserial',
                'request_id': 'text',
                'workspace_id': 'uuid'},
 'chains': {'capabilities': 'jsonb',
            'chain_id': 'bigint',
            'created_at': 'timestamptz',
            'explorer': 'text',
            'id': 'uuid',
            'name': 'text',
            'native_currency': 'text',
            'status': 'text',
            'updated_at': 'timestamptz'},
 'contracts': {'address': 'text',
               'chain_id': 'uuid',
               'created_at': 'timestamptz',
               'deployment_block': 'bigint',
               'id': 'uuid',
               'protocol_id': 'uuid',
               'proxy_type': 'text',
               'verified': 'boolean'},
 'data_sources': {'attribution_required': 'boolean',
                  'authentication_type': 'text',
                  'authority_class': 'text',
                  'cache_ttl_seconds': 'int',
                  'category': 'text',
                  'commercial_tier': 'text',
                  'created_at': 'timestamptz',
                  'enabled': 'boolean',
                  'expected_freshness': 'text',
                  'id': 'uuid',
                  'license_notes': 'text',
                  'provider_id': 'text',
                  'provider_name': 'text',
                  'provider_priority': 'int',
                  'rate_limit': 'text',
                  'redistribution_policy': 'text',
                  'storage_policy': 'text',
                  'supported_chains': 'jsonb',
                  'supported_engines': 'jsonb',
                  'updated_at': 'timestamptz'},
 'decision_reasons': {'decision_id': 'uuid', 'dimension': 'text', 'id': 'uuid', 'material': 'boolean', 'rank': 'int', 'reason': 'text'},
 'decisions': {'analysis_id': 'uuid',
               'created_at': 'timestamptz',
               'data_confidence': 'numeric',
               'decision': 'text',
               'decision_confidence': 'numeric',
               'id': 'uuid',
               'policy_version': 'text',
               'recommended_action': 'text',
               'risk_score': 'numeric',
               'safer_option': 'text'},
 'defi_positions': {'collateral_asset_id': 'uuid',
                    'collateral_value': 'numeric',
                    'created_at': 'timestamptz',
                    'debt_asset_id': 'uuid',
                    'debt_value': 'numeric',
                    'health_factor': 'numeric',
                    'id': 'uuid',
                    'liquidation_threshold': 'numeric',
                    'ltv': 'numeric',
                    'market': 'text',
                    'observed_at': 'timestamptz',
                    'protocol_id': 'uuid',
                    'workspace_id': 'uuid'},
 'engine_results': {'assumptions': 'jsonb',
                    'calculation_version': 'text',
                    'created_at': 'timestamptz',
                    'data_confidence': 'numeric',
                    'engine_confidence': 'numeric',
                    'engine_run_id': 'uuid',
                    'hard_blockers': 'jsonb',
                    'id': 'uuid',
                    'metrics': 'jsonb',
                    'mitigations': 'jsonb',
                    'provider_consensus': 'text',
                    'risk_score': 'numeric',
                    'severity': 'text',
                    'signals': 'jsonb',
                    'summary': 'text',
                    'warnings': 'jsonb'},
 'engine_runs': {'analysis_id': 'uuid',
                 'completed_at': 'timestamptz',
                 'duration_ms': 'numeric',
                 'engine_id': 'text',
                 'engine_version': 'text',
                 'id': 'uuid',
                 'started_at': 'timestamptz',
                 'status': 'text'},
 'entities': {'canonical_name': 'text', 'created_at': 'timestamptz', 'entity_type': 'text', 'id': 'uuid', 'updated_at': 'timestamptz'},
 'entity_labels': {'address': 'text',
                   'chain_id': 'uuid',
                   'confidence': 'numeric',
                   'entity_id': 'uuid',
                   'id': 'uuid',
                   'label': 'text',
                   'observed_at': 'timestamptz',
                   'provider_id': 'uuid',
                   'retrieved_at': 'timestamptz',
                   'verified': 'boolean'},
 'evidence': {'analysis_id': 'uuid',
              'asset_id': 'uuid',
              'block_number': 'bigint',
              'calculation_version': 'text',
              'chain_id': 'uuid',
              'confidence': 'numeric',
              'created_at': 'timestamptz',
              'engine_run_id': 'uuid',
              'engine_version': 'text',
              'freshness': 'text',
              'id': 'uuid',
              'license_classification': 'text',
              'normalized_value': 'jsonb',
              'observed_at': 'timestamptz',
              'protocol_id': 'uuid',
              'provider_endpoint': 'text',
              'provider_id': 'uuid',
              'provider_request_id': 'text',
              'raw_reference': 'text',
              'retrieved_at': 'timestamptz',
              'source_type': 'text'},
 'findings': {'analysis_id': 'uuid',
              'created_at': 'timestamptz',
              'detail': 'text',
              'engine_run_id': 'uuid',
              'finding_type': 'text',
              'id': 'uuid',
              'severity': 'text',
              'title': 'text'},
 'fund_flows': {'amount': 'numeric',
                'analysis_id': 'uuid',
                'asset_id': 'uuid',
                'from_entity': 'uuid',
                'id': 'uuid',
                'observed_at': 'timestamptz',
                'provider_id': 'uuid',
                'to_entity': 'uuid',
                'tx_hash': 'text',
                'usd_value': 'numeric'},
 'monitors': {'created_at': 'timestamptz',
              'enabled': 'boolean',
              'entity_ref': 'text',
              'entity_type': 'text',
              'id': 'uuid',
              'rules': 'jsonb',
              'thresholds': 'jsonb',
              'updated_at': 'timestamptz',
              'workspace_id': 'uuid'},
 'notification_preferences': {'channel': 'text',
                              'config': 'jsonb',
                              'enabled': 'boolean',
                              'id': 'uuid',
                              'severity_threshold': 'text',
                              'workspace_id': 'uuid'},
 'oracle_feeds': {'asset_id': 'uuid',
                  'chain_id': 'uuid',
                  'contract_address': 'text',
                  'id': 'uuid',
                  'metadata': 'jsonb',
                  'oracle_type': 'text',
                  'protocol_id': 'uuid',
                  'provider_id': 'uuid'},
 'oracle_observations': {'block_number': 'bigint',
                         'freshness': 'text',
                         'id': 'uuid',
                         'observed_at': 'timestamptz',
                         'oracle_feed_id': 'uuid',
                         'retrieved_at': 'timestamptz',
                         'value': 'numeric'},
 'organization_members': {'created_at': 'timestamptz', 'organization_id': 'uuid', 'role': 'text', 'user_id': 'uuid'},
 'organizations': {'created_at': 'timestamptz', 'id': 'uuid', 'name': 'text', 'updated_at': 'timestamptz'},
 'portfolio_positions': {'asset_id': 'uuid',
                         'chain_id': 'uuid',
                         'counterparty': 'text',
                         'id': 'uuid',
                         'observed_at': 'timestamptz',
                         'portfolio_id': 'uuid',
                         'price': 'numeric',
                         'protocol_id': 'uuid',
                         'quantity': 'numeric',
                         'source': 'text',
                         'value_usd': 'numeric'},
 'portfolios': {'created_at': 'timestamptz',
                'id': 'uuid',
                'name': 'text',
                'updated_at': 'timestamptz',
                'valuation_currency': 'text',
                'workspace_id': 'uuid'},
 'prices': {'asset_id': 'uuid',
            'block_number': 'bigint',
            'confidence': 'numeric',
            'freshness': 'text',
            'id': 'uuid',
            'observed_at': 'timestamptz',
            'price': 'numeric',
            'provider_id': 'uuid',
            'quote_currency': 'text',
            'retrieved_at': 'timestamptz'},
 'profiles': {'created_at': 'timestamptz',
              'display_name': 'text',
              'onboarding_complete': 'boolean',
              'updated_at': 'timestamptz',
              'user_id': 'uuid',
              'user_role': 'text'},
 'protocol_assessments': {'analysis_id': 'uuid',
                          'contagion_risk': 'numeric',
                          'created_at': 'timestamptz',
                          'dependency_risk': 'numeric',
                          'economic_risk': 'numeric',
                          'governance_risk': 'numeric',
                          'id': 'uuid',
                          'liquidity_risk': 'numeric',
                          'market_risk': 'numeric',
                          'oracle_risk': 'numeric',
                          'overall_risk': 'numeric',
                          'protocol_id': 'uuid',
                          'smart_contract_risk': 'numeric'},
 'protocol_metrics': {'chain_id': 'uuid',
                      'id': 'uuid',
                      'methodology': 'text',
                      'metric': 'text',
                      'observed_at': 'timestamptz',
                      'protocol_id': 'uuid',
                      'provider_id': 'uuid',
                      'retrieved_at': 'timestamptz',
                      'unit': 'text',
                      'value': 'numeric'},
 'protocols': {'category': 'text',
               'created_at': 'timestamptz',
               'id': 'uuid',
               'name': 'text',
               'slug': 'text',
               'updated_at': 'timestamptz',
               'website': 'text'},
 'provider_connections': {'config': 'jsonb',
                          'created_at': 'timestamptz',
                          'credential_reference': 'text',
                          'id': 'uuid',
                          'provider_id': 'uuid',
                          'status': 'text',
                          'updated_at': 'timestamptz',
                          'workspace_id': 'uuid'},
 'provider_health_checks': {'checked_at': 'timestamptz',
                            'id': 'bigserial',
                            'latency_ms': 'numeric',
                            'message': 'text',
                            'provider_id': 'uuid',
                            'status': 'text'},
 'provider_requests': {'analysis_id': 'uuid',
                       'created_at': 'timestamptz',
                       'endpoint': 'text',
                       'error_class': 'text',
                       'estimated_cost': 'numeric',
                       'id': 'uuid',
                       'latency_ms': 'numeric',
                       'observed_at': 'timestamptz',
                       'provider_id': 'uuid',
                       'request_id_external': 'text',
                       'retrieved_at': 'timestamptz',
                       'status': 'text'},
 'reports': {'analysis_id': 'uuid',
             'created_at': 'timestamptz',
             'decision_id': 'uuid',
             'format': 'text',
             'id': 'uuid',
             'status': 'text',
             'storage_ref': 'text',
             'workspace_id': 'uuid'},
 'route_steps': {'contract_address': 'text',
                 'expected_seconds': 'int',
                 'fee_usd': 'numeric',
                 'id': 'uuid',
                 'metadata': 'jsonb',
                 'provider_name': 'text',
                 'route_id': 'uuid',
                 'step_index': 'int',
                 'step_type': 'text'},
 'routes': {'analysis_id': 'uuid',
            'destination_asset_id': 'uuid',
            'destination_chain_id': 'uuid',
            'duration_seconds': 'int',
            'expected_received': 'numeric',
            'id': 'uuid',
            'observed_at': 'timestamptz',
            'provider_id': 'uuid',
            'recommended': 'boolean',
            'retrieved_at': 'timestamptz',
            'risk_score': 'numeric',
            'source_asset_id': 'uuid',
            'source_chain_id': 'uuid',
            'total_fee_usd': 'numeric'},
 'saved_analyses': {'analysis_id': 'uuid',
                    'archived': 'boolean',
                    'created_at': 'timestamptz',
                    'id': 'uuid',
                    'name': 'text',
                    'tags': 'text[]',
                    'workspace_id': 'uuid'},
 'security_assessments': {'analysis_id': 'uuid',
                          'created_at': 'timestamptz',
                          'hard_blocker': 'boolean',
                          'id': 'uuid',
                          'risk_score': 'numeric',
                          'severity': 'text'},
 'security_signals': {'affected_address': 'text',
                      'affected_asset': 'uuid',
                      'assessment_id': 'uuid',
                      'confidence': 'numeric',
                      'explanation': 'text',
                      'id': 'uuid',
                      'observed_at': 'timestamptz',
                      'provider_id': 'uuid',
                      'severity': 'text',
                      'signal_type': 'text'},
 'simulations': {'analysis_id': 'uuid',
                 'gas_estimate': 'numeric',
                 'id': 'uuid',
                 'observed_at': 'timestamptz',
                 'provider_id': 'uuid',
                 'result': 'jsonb',
                 'retrieved_at': 'timestamptz',
                 'revert_reason': 'text',
                 'state_block': 'bigint',
                 'success': 'boolean',
                 'transaction_id': 'uuid'},
 'source_conflicts': {'analysis_id': 'uuid',
                      'created_at': 'timestamptz',
                      'difference': 'numeric',
                      'difference_percentage': 'numeric',
                      'expected_tolerance': 'numeric',
                      'id': 'uuid',
                      'metric': 'text',
                      'resolution_confidence': 'numeric',
                      'resolution_method': 'text',
                      'resolved_value': 'jsonb',
                      'severity': 'text',
                      'source_a': 'uuid',
                      'source_b': 'uuid',
                      'value_a': 'jsonb',
                      'value_b': 'jsonb'},
 'threat_events': {'affected_entity': 'text',
                   'confidence': 'numeric',
                   'created_at': 'timestamptz',
                   'estimated_exposure': 'numeric',
                   'event_type': 'text',
                   'id': 'uuid',
                   'monitor_id': 'uuid',
                   'observed_at': 'timestamptz',
                   'provider_id': 'uuid',
                   'severity': 'text',
                   'status': 'text'},
 'tokens': {'asset_id': 'uuid', 'chain_id': 'uuid', 'contract_address': 'text', 'decimals': 'int', 'id': 'uuid'},
 'transaction_traces': {'call_type': 'text',
                        'from_address': 'text',
                        'gas_used': 'numeric',
                        'id': 'uuid',
                        'parent_trace_id': 'uuid',
                        'revert_reason': 'text',
                        'success': 'boolean',
                        'to_address': 'text',
                        'trace_index': 'int',
                        'transaction_id': 'uuid',
                        'value': 'numeric'},
 'transactions': {'block_number': 'bigint',
                  'chain_id': 'uuid',
                  'created_at': 'timestamptz',
                  'from_address': 'text',
                  'gas_limit': 'numeric',
                  'gas_price': 'numeric',
                  'id': 'uuid',
                  'native_value': 'numeric',
                  'nonce': 'bigint',
                  'observed_at': 'timestamptz',
                  'to_address': 'text',
                  'tx_hash': 'text'},
 'transfers': {'amount': 'numeric',
               'asset_id': 'uuid',
               'chain_id': 'uuid',
               'from_address': 'text',
               'id': 'uuid',
               'observed_at': 'timestamptz',
               'provider_id': 'uuid',
               'to_address': 'text',
               'transaction_id': 'uuid',
               'usd_value': 'numeric'},
 'treasury_scenarios': {'assumptions': 'jsonb',
                        'created_at': 'timestamptz',
                        'id': 'uuid',
                        'name': 'text',
                        'result': 'jsonb',
                        'shocks': 'jsonb',
                        'workspace_id': 'uuid'},
 'user_risk_policies': {'allowed_chains': 'jsonb',
                        'allowed_protocols': 'jsonb',
                        'id': 'uuid',
                        'max_overall_risk': 'numeric',
                        'maximum_concentration': 'numeric',
                        'minimum_liquidity_reserve': 'numeric',
                        'policy': 'jsonb',
                        'prohibited_dependencies': 'jsonb',
                        'updated_at': 'timestamptz',
                        'workspace_id': 'uuid'},
 'users': {'created_at': 'timestamptz', 'email': 'text', 'id': 'uuid', 'password_hash': 'text', 'updated_at': 'timestamptz'},
 'wallet_groups': {'created_at': 'timestamptz', 'id': 'uuid', 'name': 'text', 'workspace_id': 'uuid'},
 'wallets': {'address': 'text', 'chain_id': 'uuid', 'created_at': 'timestamptz', 'id': 'uuid', 'label': 'text', 'workspace_id': 'uuid'},
 'workspaces': {'created_at': 'timestamptz',
                'id': 'uuid',
                'name': 'text',
                'organization_id': 'uuid',
                'owner_user_id': 'uuid',
                'role_context': 'text',
                'settings': 'jsonb',
                'updated_at': 'timestamptz'},
 'yield_strategies': {'asset_id': 'uuid',
                      'base_yield': 'numeric',
                      'created_at': 'timestamptz',
                      'id': 'uuid',
                      'incentive_yield': 'numeric',
                      'lock_period_seconds': 'bigint',
                      'observed_at': 'timestamptz',
                      'pool_ref': 'text',
                      'protocol_id': 'uuid',
                      'vault_ref': 'text',
                      'workspace_id': 'uuid'}}
EXPECTED_FKS=[('profiles', ('user_id',), 'users', ('id',), 'CASCADE'),
 ('organization_members', ('organization_id',), 'organizations', ('id',), 'CASCADE'),
 ('organization_members', ('user_id',), 'users', ('id',), 'CASCADE'),
 ('workspaces', ('organization_id',), 'organizations', ('id',), None),
 ('workspaces', ('owner_user_id',), 'users', ('id',), None),
 ('tokens', ('asset_id',), 'assets', ('id',), None),
 ('tokens', ('chain_id',), 'chains', ('id',), None),
 ('contracts', ('chain_id',), 'chains', ('id',), None),
 ('contracts', ('protocol_id',), 'protocols', ('id',), None),
 ('wallets', ('workspace_id',), 'workspaces', ('id',), 'CASCADE'),
 ('wallets', ('chain_id',), 'chains', ('id',), None),
 ('wallet_groups', ('workspace_id',), 'workspaces', ('id',), 'CASCADE'),
 ('provider_connections', ('workspace_id',), 'workspaces', ('id',), None),
 ('provider_connections', ('provider_id',), 'data_sources', ('id',), None),
 ('provider_health_checks', ('provider_id',), 'data_sources', ('id',), None),
 ('provider_requests', ('provider_id',), 'data_sources', ('id',), None),
 ('analyses', ('workspace_id',), 'workspaces', ('id',), None),
 ('analyses', ('chain_id',), 'chains', ('id',), None),
 ('engine_runs', ('analysis_id',), 'analyses', ('id',), 'CASCADE'),
 ('engine_results', ('engine_run_id',), 'engine_runs', ('id',), 'CASCADE'),
 ('decisions', ('analysis_id',), 'analyses', ('id',), 'CASCADE'),
 ('decision_reasons', ('decision_id',), 'decisions', ('id',), 'CASCADE'),
 ('findings', ('analysis_id',), 'analyses', ('id',), 'CASCADE'),
 ('findings', ('engine_run_id',), 'engine_runs', ('id',), None),
 ('evidence', ('analysis_id',), 'analyses', ('id',), 'CASCADE'),
 ('evidence', ('engine_run_id',), 'engine_runs', ('id',), None),
 ('evidence', ('provider_id',), 'data_sources', ('id',), None),
 ('evidence', ('chain_id',), 'chains', ('id',), None),
 ('evidence', ('asset_id',), 'assets', ('id',), None),
 ('evidence', ('protocol_id',), 'protocols', ('id',), None),
 ('source_conflicts', ('analysis_id',), 'analyses', ('id',), 'CASCADE'),
 ('source_conflicts', ('source_a',), 'data_sources', ('id',), None),
 ('source_conflicts', ('source_b',), 'data_sources', ('id',), None),
 ('transactions', ('chain_id',), 'chains', ('id',), None),
 ('transaction_traces', ('transaction_id',), 'transactions', ('id',), 'CASCADE'),
 ('transfers', ('transaction_id',), 'transactions', ('id',), None),
 ('transfers', ('chain_id',), 'chains', ('id',), None),
 ('transfers', ('asset_id',), 'assets', ('id',), None),
 ('transfers', ('provider_id',), 'data_sources', ('id',), None),
 ('simulations', ('analysis_id',), 'analyses', ('id',), None),
 ('simulations', ('transaction_id',), 'transactions', ('id',), None),
 ('simulations', ('provider_id',), 'data_sources', ('id',), None),
 ('security_assessments', ('analysis_id',), 'analyses', ('id',), None),
 ('security_signals', ('assessment_id',), 'security_assessments', ('id',), 'CASCADE'),
 ('security_signals', ('provider_id',), 'data_sources', ('id',), None),
 ('security_signals', ('affected_asset',), 'assets', ('id',), None),
 ('monitors', ('workspace_id',), 'workspaces', ('id',), None),
 ('threat_events', ('monitor_id',), 'monitors', ('id',), None),
 ('threat_events', ('provider_id',), 'data_sources', ('id',), None),
 ('alerts', ('workspace_id',), 'workspaces', ('id',), None),
 ('alerts', ('threat_event_id',), 'threat_events', ('id',), None),
 ('entity_labels', ('entity_id',), 'entities', ('id',), None),
 ('entity_labels', ('chain_id',), 'chains', ('id',), None),
 ('entity_labels', ('provider_id',), 'data_sources', ('id',), None),
 ('fund_flows', ('analysis_id',), 'analyses', ('id',), None),
 ('fund_flows', ('from_entity',), 'entities', ('id',), None),
 ('fund_flows', ('to_entity',), 'entities', ('id',), None),
 ('fund_flows', ('asset_id',), 'assets', ('id',), None),
 ('fund_flows', ('provider_id',), 'data_sources', ('id',), None),
 ('routes', ('analysis_id',), 'analyses', ('id',), None),
 ('routes', ('provider_id',), 'data_sources', ('id',), None),
 ('routes', ('source_chain_id',), 'chains', ('id',), None),
 ('routes', ('destination_chain_id',), 'chains', ('id',), None),
 ('routes', ('source_asset_id',), 'assets', ('id',), None),
 ('routes', ('destination_asset_id',), 'assets', ('id',), None),
 ('route_steps', ('route_id',), 'routes', ('id',), 'CASCADE'),
 ('prices', ('asset_id',), 'assets', ('id',), None),
 ('prices', ('provider_id',), 'data_sources', ('id',), None),
 ('oracle_feeds', ('chain_id',), 'chains', ('id',), None),
 ('oracle_feeds', ('protocol_id',), 'protocols', ('id',), None),
 ('oracle_feeds', ('asset_id',), 'assets', ('id',), None),
 ('oracle_feeds', ('provider_id',), 'data_sources', ('id',), None),
 ('oracle_observations', ('oracle_feed_id',), 'oracle_feeds', ('id',), None),
 ('portfolios', ('workspace_id',), 'workspaces', ('id',), None),
 ('portfolio_positions', ('portfolio_id',), 'portfolios', ('id',), 'CASCADE'),
 ('portfolio_positions', ('asset_id',), 'assets', ('id',), None),
 ('portfolio_positions', ('chain_id',), 'chains', ('id',), None),
 ('portfolio_positions', ('protocol_id',), 'protocols', ('id',), None),
 ('protocol_metrics', ('protocol_id',), 'protocols', ('id',), None),
 ('protocol_metrics', ('chain_id',), 'chains', ('id',), None),
 ('protocol_metrics', ('provider_id',), 'data_sources', ('id',), None),
 ('protocol_assessments', ('analysis_id',), 'analyses', ('id',), None),
 ('protocol_assessments', ('protocol_id',), 'protocols', ('id',), None),
 ('defi_positions', ('workspace_id',), 'workspaces', ('id',), None),
 ('defi_positions', ('protocol_id',), 'protocols', ('id',), None),
 ('defi_positions', ('collateral_asset_id',), 'assets', ('id',), None),
 ('defi_positions', ('debt_asset_id',), 'assets', ('id',), None),
 ('yield_strategies', ('workspace_id',), 'workspaces', ('id',), None),
 ('yield_strategies', ('protocol_id',), 'protocols', ('id',), None),
 ('yield_strategies', ('asset_id',), 'assets', ('id',), None),
 ('treasury_scenarios', ('workspace_id',), 'workspaces', ('id',), None),
 ('saved_analyses', ('workspace_id',), 'workspaces', ('id',), None),
 ('saved_analyses', ('analysis_id',), 'analyses', ('id',), None),
 ('reports', ('workspace_id',), 'workspaces', ('id',), None),
 ('reports', ('analysis_id',), 'analyses', ('id',), None),
 ('reports', ('decision_id',), 'decisions', ('id',), None),
 ('user_risk_policies', ('workspace_id',), 'workspaces', ('id',), None),
 ('notification_preferences', ('workspace_id',), 'workspaces', ('id',), None),
 ('audit_logs', ('workspace_id',), 'workspaces', ('id',), None),
 ('audit_logs', ('actor_user_id',), 'users', ('id',), None)]
EXPECTED_UNIQUES=[('users', ('email',)),
 ('chains', ('chain_id',)),
 ('chains', ('name',)),
 ('assets', ('canonical_identifier',)),
 ('tokens', ('chain_id', 'contract_address')),
 ('protocols', ('slug',)),
 ('contracts', ('chain_id', 'address')),
 ('wallets', ('workspace_id', 'chain_id', 'address')),
 ('data_sources', ('provider_id',)),
 ('provider_connections', ('workspace_id', 'provider_id')),
 ('engine_runs', ('analysis_id', 'engine_id')),
 ('engine_results', ('engine_run_id',)),
 ('decision_reasons', ('decision_id', 'rank')),
 ('transactions', ('chain_id', 'tx_hash')),
 ('transaction_traces', ('transaction_id', 'trace_index')),
 ('route_steps', ('route_id', 'step_index')),
 ('portfolio_positions', ('portfolio_id', 'asset_id', 'chain_id', 'protocol_id')),
 ('saved_analyses', ('workspace_id', 'analysis_id')),
 ('user_risk_policies', ('workspace_id',)),
 ('notification_preferences', ('workspace_id', 'channel'))]
EXPLICIT_INDEXES=[('workspaces_owner_idx', 'workspaces', ('owner_user_id',), False),
 ('provider_health_provider_time_idx', 'provider_health_checks', ('provider_id', 'checked_at'), False),
 ('analyses_workspace_time_idx', 'analyses', ('workspace_id', 'created_at'), False),
 ('evidence_analysis_idx', 'evidence', ('analysis_id',), False),
 ('prices_asset_time_idx', 'prices', ('asset_id', 'observed_at'), False),
 ('audit_logs_workspace_time_idx', 'audit_logs', ('workspace_id', 'created_at'), False)]

def _type(code,dialect):
    # 0001-0003 create every primary key and the initial relationships as
    # String(36), including on PostgreSQL. Match that existing representation
    # for new ID columns so FK constraints are valid on a fresh PG database.
    if code=="uuid": return sa.String(36)
    if code in {"bigserial","bigint"}: return sa.BigInteger()
    if code in {"int","integer"}: return sa.Integer()
    if code=="numeric": return sa.Numeric()
    if code=="boolean": return sa.Boolean()
    if code=="timestamptz": return sa.DateTime(timezone=True)
    if code=="jsonb": return postgresql.JSONB() if dialect=="postgresql" else sa.Text()
    if code=="text[]": return postgresql.ARRAY(sa.Text()) if dialect=="postgresql" else sa.Text()
    return sa.Text()

def _fk_edges(inspector,table):
    return {(tuple(x.get("constrained_columns") or []),x.get("referred_table"),tuple(x.get("referred_columns") or [])) for x in inspector.get_foreign_keys(table)}

def _unique_sets(inspector,table):
    out={tuple(x.get("column_names") or []) for x in inspector.get_unique_constraints(table) if x.get("column_names")}
    out.update(tuple(x.get("column_names") or []) for x in inspector.get_indexes(table) if x.get("unique") and x.get("column_names"))
    return out

def _constraint_name(value):
    # PostgreSQL identifiers are limited to 63 bytes; retain a stable suffix
    # to avoid collisions when a blueprint relationship name is longer.
    if len(value.encode("utf-8")) <= 63: return value
    return value[:54] + "_" + hashlib.sha1(value.encode("utf-8")).hexdigest()[:8]

def upgrade():
    bind=op.get_bind();dialect=bind.dialect.name;inspector=inspect(bind)
    for table,spec in EXPECTED_COLUMNS.items():
        existing={c["name"] for c in inspector.get_columns(table)}
        for name,code in spec.items():
            if name not in existing: op.add_column(table,sa.Column(name,_type(code,dialect),nullable=True))
        inspector=inspect(bind)
    by_fk={}
    for table,local,ref,remote,ondelete in EXPECTED_FKS:by_fk.setdefault(table,[]).append((local,ref,remote,ondelete))
    by_unique={}
    for table,columns in EXPECTED_UNIQUES:by_unique.setdefault(table,[]).append(columns)
    for table in EXPECTED_COLUMNS:
        inspector=inspect(bind);current_fk=_fk_edges(inspector,table);current_unique=_unique_sets(inspector,table)
        missing_fk=[x for x in by_fk.get(table,[]) if (tuple(x[0]),x[1],tuple(x[2])) not in current_fk]
        missing_unique=[x for x in by_unique.get(table,[]) if tuple(x) not in current_unique]
        if not missing_fk and not missing_unique:continue
        with op.batch_alter_table(table,recreate="always" if dialect=="sqlite" else "auto") as batch:
            for local,ref,remote,ondelete in missing_fk:
                batch.create_foreign_key(_constraint_name("fk_"+table+"_"+"_".join(local)+"__"+ref),ref,list(local),list(remote),ondelete=ondelete)
            for columns in missing_unique:
                batch.create_unique_constraint(_constraint_name("uq_"+table+"_"+"_".join(columns)),list(columns))
    inspector=inspect(bind)
    for name,table,columns,unique in EXPLICIT_INDEXES:
        if name not in {x["name"] for x in inspector.get_indexes(table)}:op.create_index(name,table,list(columns),unique=unique)
        inspector=inspect(bind)
    # A dedicated migration role owns the application tables, not Supabase's
    # public schema. COMMENT ON SCHEMA would require schema ownership and is
    # not part of the application contract.

P3_OPERATIONAL_COLUMNS={
    "users":{"id","email","password_hash","role","token_version","created_at"},
    "organizations":{"id","name","created_at"},
    "organization_members":{"organization_id","user_id","role","created_at"},
    "workspaces":{"id","owner_user_id","organization_id","name","role","created_at"},
    "analyses":{"id","engine_id","payload","demo","created_at","owner_user_id","workspace_id"},
    "decisions":{"id","payload","created_at","owner_user_id","workspace_id"},
    "saved_analyses":{"id","user_id","analysis_id","title","archived","created_at","workspace_id"},
    "portfolios":{"id","owner_user_id","name","payload","created_at","workspace_id"},
    "monitors":{"id","workspace_id","created_by_user_id","entity","chain","rules","config","status","last_snapshot","last_analysis_id","last_status","created_at","updated_at"},
    "alerts":{"id","workspace_id","monitor_id","analysis_id","severity","status","payload","created_at","updated_at"},
    "reports":{"id","workspace_id","decision_id","format","status","created_by_user_id","created_at"},
    "audit_logs":{"id","actor","actor_user_id","workspace_id","request_id","action","resource_type","resource_id","detail","created_at"},
}

def downgrade():
    bind=op.get_bind();dialect=bind.dialect.name
    inspector=inspect(bind)
    for name,table,columns,unique in EXPLICIT_INDEXES:
        if table in P3_OPERATIONAL_COLUMNS and name in {x["name"] for x in inspector.get_indexes(table)}:
            op.drop_index(name,table_name=table)
            inspector=inspect(bind)
    for table,keep in P3_OPERATIONAL_COLUMNS.items():
        inspector=inspect(bind)
        fk_names=[x.get("name") for x in inspector.get_foreign_keys(table) if (x.get("name") or "").startswith("fk_"+table+"_") and "__" in (x.get("name") or "")]
        uq_names=[x.get("name") for x in inspector.get_unique_constraints(table) if (x.get("name") or "").startswith("uq_"+table+"_")]
        current={c["name"] for c in inspector.get_columns(table)}
        extra=sorted((set(EXPECTED_COLUMNS.get(table,{}))-keep) & current)
        if not fk_names and not uq_names and not extra: continue
        with op.batch_alter_table(table,recreate="always" if dialect=="sqlite" else "auto") as batch:
            for name in fk_names: batch.drop_constraint(name,type_="foreignkey")
            for name in uq_names: batch.drop_constraint(name,type_="unique")
            for column in extra: batch.drop_column(column)
